#!/usr/bin/env bash
#
# check-x509-ext-vectors.sh — prove kernel/net/x509_ext_vectors.h is
# exactly what its generator produces.
#
# WHY THIS EXISTS
#   x509_ext_vectors.h is generated by tools/test/gen-x509-ext-vectors.py
#   and then clang-format'ed. Nothing stops someone hand-editing the
#   committed header — and a hand-edited EXPECTATION is worse than no
#   test, because it looks like coverage while asserting whatever the
#   editor wanted. It also caught a real defect: the generator wrote its
#   banner through Windows' cp1252 stdout, so the committed header held a
#   lone 0x97 byte and was not valid UTF-8 at all.
#
#   So this checks three things the header must satisfy:
#     1. regenerating + clang-format reproduces it byte for byte,
#     2. it is valid UTF-8,
#     3. it has LF line endings only.
#
# USAGE
#   tools/test/check-x509-ext-vectors.sh          # from the repo root
#
# EXIT STATUS
#   0  header matches its generator and is clean
#   1  header is stale, hand-edited, or mis-encoded (diff printed)
#
# Run it after touching the generator, and any time the header changes.

set -u

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT" || exit 1

HEADER="kernel/net/x509_ext_vectors.h"
GEN="tools/test/gen-x509-ext-vectors.py"
PYTHON="${PYTHON:-python3}"
command -v "$PYTHON" >/dev/null 2>&1 || PYTHON=python

rc=0
# The scratch copy lives NEXT TO the header, inside the tree, so
# clang-format's usual walk-up finds the repo .clang-format on its own.
# Passing --style=file:<path> instead would break under MSYS/Git Bash,
# where a native clang-format.exe cannot read a /c/... style path.
tmp="$(dirname "$HEADER")/.x509_ext_vectors.regen.h"
trap 'rm -f "$tmp"' EXIT

# 1. The generator must succeed. It self-checks every vector's stated
#    verdict against an independent mirror decoder before emitting, so a
#    non-zero exit here means a vector and its expectation disagree.
if ! "$PYTHON" "$GEN" > "$tmp"; then
    echo "FAIL: $GEN exited non-zero (vector self-check failed)"
    exit 1
fi

# 2. Byte-for-byte reproduction, after the same clang-format pass the
#    committed header went through.
if command -v clang-format >/dev/null 2>&1; then
    clang-format -i "$tmp"
else
    echo "WARN: clang-format not found; comparing unformatted output"
fi

if ! diff -u "$HEADER" "$tmp"; then
    echo "FAIL: $HEADER does not match its generator."
    echo "      Regenerate with:  $PYTHON $GEN > $HEADER && clang-format -i $HEADER"
    rc=1
else
    echo "OK: $HEADER reproduces exactly from $GEN"
fi

# 3. Encoding hygiene — the kernel compiles this file.
if ! "$PYTHON" - "$HEADER" <<'PY'
import sys
data = open(sys.argv[1], "rb").read()
ok = True
try:
    data.decode("utf-8")
except UnicodeDecodeError as e:
    print(f"FAIL: {sys.argv[1]} is not valid UTF-8: {e}")
    ok = False
if b"\r" in data:
    print(f"FAIL: {sys.argv[1]} contains CR bytes (DuetOS is LF-only)")
    ok = False
if ok:
    print(f"OK: {sys.argv[1]} is valid UTF-8 with LF line endings")
sys.exit(0 if ok else 1)
PY
then
    rc=1
fi

exit $rc
