#!/usr/bin/env python3
"""Generate the RSA-4096 known-answer vector for the bigint self-test.

Why this exists
---------------
The kernel bigint (kernel/crypto/bigint.{h,cpp}) is a fixed 4096-bit
fixed-width integer. RSA-4096 verification squares a 4096-bit modulus,
which needs an 8192-bit intermediate product. Before the double-width
accumulator landed, that product tripped the "Mul carry overflow"
KASSERT and panicked. The bigint self-test embeds a real RSA-4096
known-answer vector so that path is exercised on every boot.

This script regenerates that vector with host OpenSSL and emits the
C++ header consumed by kernel/crypto/bigint.cpp's self-test:

    tools/test/gen-rsa4096-vector.py > \
        kernel/crypto/bigint_rsa4096_vector.h
    clang-format -i kernel/crypto/bigint_rsa4096_vector.h

(the emitted array layout is 12-per-row; clang-format repacks it to
the project's 120-col style, so always run clang-format afterwards.)

Provenance is host OpenSSL (`openssl genrsa 4096`, e=65537; the message
is signed with `openssl dgst -sha256 -sign`, i.e. PKCS#1 v1.5 / SHA-256).
The committed header is one frozen instance — re-running this produces a
*different* key (fresh randomness) but the same shape, and the script's
own assertions prove the EM is a well-formed EMSA-PKCS1-v1_5 wrap.

Dependencies: openssl in $PATH, python3. No third-party packages.
"""

import hashlib
import subprocess
import sys
import tempfile
import os

SHA256_DIGESTINFO_PREFIX = bytes.fromhex("3031300d060960864801650304020105000420")
MESSAGE = b"DuetOS RSA-4096 bigint known-answer vector"


def c_array(name: str, data: bytes) -> str:
    rows = []
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        rows.append("    " + ", ".join("0x%02x" % b for b in chunk) + ",")
    body = "\n".join(rows)
    return f"inline constexpr u8 {name}[{len(data)}] = {{\n{body}\n}};"


def main() -> int:
    workdir = tempfile.mkdtemp(prefix="rsa4096-vec-")
    key = os.path.join(workdir, "key.pem")
    msg = os.path.join(workdir, "msg.bin")
    sig = os.path.join(workdir, "sig.bin")

    subprocess.check_call(
        ["openssl", "genrsa", "-out", key, "4096"],
        stderr=subprocess.DEVNULL,
    )
    modulus_line = subprocess.check_output(
        ["openssl", "rsa", "-in", key, "-noout", "-modulus"]
    ).decode()
    n = int(modulus_line.strip().split("=", 1)[1], 16)
    e = 65537

    with open(msg, "wb") as f:
        f.write(MESSAGE)
    subprocess.check_call(
        ["openssl", "dgst", "-sha256", "-sign", key, "-out", sig, msg]
    )
    sig_bytes = open(sig, "rb").read()
    s = int.from_bytes(sig_bytes, "big")

    # RSAVP1: m = s^e mod n — exactly what the kernel computes.
    m = pow(s, e, n)
    k = (n.bit_length() + 7) // 8
    em = m.to_bytes(k, "big")
    digest = hashlib.sha256(MESSAGE).digest()

    # Prove the recovered EM is a valid EMSA-PKCS1-v1_5 SHA-256 wrap.
    assert em[0] == 0x00 and em[1] == 0x01, em[:4].hex()
    assert em.endswith(digest), "digest tail mismatch"
    idx = em.index(SHA256_DIGESTINFO_PREFIX)
    assert em[idx - 1] == 0x00, "missing 0x00 separator before DigestInfo"

    n_bytes = n.to_bytes(k, "big")

    out = sys.stdout
    out.write("#pragma once\n\n")
    out.write("// AUTO-GENERATED by tools/test/gen-rsa4096-vector.py — do not hand-edit.\n")
    out.write("//\n")
    out.write("// RSA-4096 known-answer vector for the bigint self-test.\n")
    out.write("// Provenance: host OpenSSL (`openssl genrsa 4096`, e=65537); the\n")
    out.write("// message below is signed with `openssl dgst -sha256 -sign`\n")
    out.write("// (PKCS#1 v1.5 / SHA-256). The self-test computes sig^e mod n and\n")
    out.write("// checks it equals kRsa4096Em (the EMSA-PKCS1-v1_5 encoded message).\n")
    out.write("// This exercises the 8192-bit intermediate product that used to\n")
    out.write('// trip "Mul carry overflow" in BigIntMul.\n')
    out.write(f"// modulus bits = {n.bit_length()}, byte length = {k}\n\n")
    out.write("#include \"util/types.h\"\n\n")
    out.write("namespace duetos::crypto\n{\n\n")
    out.write(c_array("kRsa4096N", n_bytes) + "\n\n")
    out.write(c_array("kRsa4096Sig", sig_bytes) + "\n\n")
    out.write(c_array("kRsa4096Em", em) + "\n\n")
    out.write("inline constexpr u32 kRsa4096E = 65537;\n\n")
    out.write("} // namespace duetos::crypto\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
