// AUTO-GENERATED — do not edit by hand.
// Regenerate via: python3 tools/win32-compat/gen-nt-shim.py
//                 --csv tools/win32-compat/nt-syscalls-x64.csv
//                 --version 'Windows 11 and Server (11 25H2)'
//                 --out kernel/subsystems/win32/nt_syscall_table_generated.h
//
// Source data: tools/win32-compat/nt-syscalls-x64.csv (j00ru/windows-syscalls)
// Target Windows version: Windows 11 and Server (11 25H2)
// Bedrock NT calls (present in every Windows XP→Win11 25H2): 292
// CustomOS coverage: 19/292 = 6%
//
// See tools/win32-compat/README.md for the legal + design rationale.

#pragma once

#include "../../core/syscall.h"
#include "../../core/types.h"

namespace customos::subsystems::win32
{

/// Sentinel value for `NtSyscallMapping::customos_sys` indicating that
/// CustomOS has no internal SYS_* number that maps to this NT call. The
/// ntdll shim's catch-all stub returns STATUS_NOT_IMPLEMENTED for these.
inline constexpr u32 kSysNtNotImpl = 0xFFFFFFFFu;

/// One row of the NT-syscall mapping table. Used by the (future) ntdll
/// shim to route an `eax = nt_number` syscall into the matching CustomOS
/// SYS_*. Sorted by `nt_number` so the shim can binary-search.
struct NtSyscallMapping
{
    const char* nt_name;     // e.g. "NtCreateFile"
    u16 nt_number;           // syscall number on the target Windows version
    u32 customos_sys;        // matching SYS_* enumerator value, or kSysNtNotImpl
};

/// Bedrock NT syscalls — present in every Windows version from XP SP1
/// through Windows 11 25H2 / Server 2025. These are the API surface a
/// real-world Windows binary is most likely to depend on.
inline constexpr NtSyscallMapping kBedrockNtSyscalls[] = {
    {"NtAccessCheck", 0x0000, kSysNtNotImpl},
    {"NtAcceptConnectPort", 0x0002, kSysNtNotImpl},
    {"NtMapUserPhysicalPagesScatter", 0x0003, kSysNtNotImpl},
    {"NtWaitForSingleObject", 0x0004, static_cast<u32>(::customos::core::SYS_MUTEX_WAIT)},
    {"NtCallbackReturn", 0x0005, kSysNtNotImpl},
    {"NtReadFile", 0x0006, static_cast<u32>(::customos::core::SYS_FILE_READ)},
    {"NtDeviceIoControlFile", 0x0007, kSysNtNotImpl},
    {"NtWriteFile", 0x0008, static_cast<u32>(::customos::core::SYS_WRITE)},
    {"NtRemoveIoCompletion", 0x0009, kSysNtNotImpl},
    {"NtReleaseSemaphore", 0x000a, kSysNtNotImpl},
    {"NtReplyWaitReceivePort", 0x000b, kSysNtNotImpl},
    {"NtReplyPort", 0x000c, kSysNtNotImpl},
    {"NtSetInformationThread", 0x000d, kSysNtNotImpl},
    {"NtSetEvent", 0x000e, static_cast<u32>(::customos::core::SYS_EVENT_SET)},
    {"NtClose", 0x000f, static_cast<u32>(::customos::core::SYS_FILE_CLOSE)},
    {"NtQueryObject", 0x0010, kSysNtNotImpl},
    {"NtQueryInformationFile", 0x0011, static_cast<u32>(::customos::core::SYS_FILE_FSTAT)},
    {"NtOpenKey", 0x0012, kSysNtNotImpl},
    {"NtEnumerateValueKey", 0x0013, kSysNtNotImpl},
    {"NtFindAtom", 0x0014, kSysNtNotImpl},
    {"NtQueryDefaultLocale", 0x0015, kSysNtNotImpl},
    {"NtQueryKey", 0x0016, kSysNtNotImpl},
    {"NtQueryValueKey", 0x0017, kSysNtNotImpl},
    {"NtAllocateVirtualMemory", 0x0018, static_cast<u32>(::customos::core::SYS_HEAP_ALLOC)},
    {"NtQueryInformationProcess", 0x0019, kSysNtNotImpl},
    {"NtWaitForMultipleObjects32", 0x001a, kSysNtNotImpl},
    {"NtWriteFileGather", 0x001b, kSysNtNotImpl},
    {"NtSetInformationProcess", 0x001c, kSysNtNotImpl},
    {"NtCreateKey", 0x001d, kSysNtNotImpl},
    {"NtFreeVirtualMemory", 0x001e, static_cast<u32>(::customos::core::SYS_HEAP_FREE)},
    {"NtImpersonateClientOfPort", 0x001f, kSysNtNotImpl},
    {"NtReleaseMutant", 0x0020, static_cast<u32>(::customos::core::SYS_MUTEX_RELEASE)},
    {"NtQueryInformationToken", 0x0021, kSysNtNotImpl},
    {"NtRequestWaitReplyPort", 0x0022, kSysNtNotImpl},
    {"NtQueryVirtualMemory", 0x0023, kSysNtNotImpl},
    {"NtOpenThreadToken", 0x0024, kSysNtNotImpl},
    {"NtQueryInformationThread", 0x0025, kSysNtNotImpl},
    {"NtOpenProcess", 0x0026, kSysNtNotImpl},
    {"NtSetInformationFile", 0x0027, kSysNtNotImpl},
    {"NtMapViewOfSection", 0x0028, kSysNtNotImpl},
    {"NtAccessCheckAndAuditAlarm", 0x0029, kSysNtNotImpl},
    {"NtUnmapViewOfSection", 0x002a, kSysNtNotImpl},
    {"NtReplyWaitReceivePortEx", 0x002b, kSysNtNotImpl},
    {"NtTerminateProcess", 0x002c, static_cast<u32>(::customos::core::SYS_EXIT)},
    {"NtSetEventBoostPriority", 0x002d, kSysNtNotImpl},
    {"NtReadFileScatter", 0x002e, kSysNtNotImpl},
    {"NtOpenThreadTokenEx", 0x002f, kSysNtNotImpl},
    {"NtOpenProcessTokenEx", 0x0030, kSysNtNotImpl},
    {"NtQueryPerformanceCounter", 0x0031, static_cast<u32>(::customos::core::SYS_PERF_COUNTER)},
    {"NtEnumerateKey", 0x0032, kSysNtNotImpl},
    {"NtOpenFile", 0x0033, static_cast<u32>(::customos::core::SYS_FILE_OPEN)},
    {"NtDelayExecution", 0x0034, static_cast<u32>(::customos::core::SYS_SLEEP_MS)},
    {"NtQueryDirectoryFile", 0x0035, kSysNtNotImpl},
    {"NtQuerySystemInformation", 0x0036, kSysNtNotImpl},
    {"NtOpenSection", 0x0037, kSysNtNotImpl},
    {"NtQueryTimer", 0x0038, kSysNtNotImpl},
    {"NtFsControlFile", 0x0039, kSysNtNotImpl},
    {"NtWriteVirtualMemory", 0x003a, kSysNtNotImpl},
    {"NtCloseObjectAuditAlarm", 0x003b, kSysNtNotImpl},
    {"NtDuplicateObject", 0x003c, kSysNtNotImpl},
    {"NtQueryAttributesFile", 0x003d, kSysNtNotImpl},
    {"NtClearEvent", 0x003e, kSysNtNotImpl},
    {"NtReadVirtualMemory", 0x003f, kSysNtNotImpl},
    {"NtOpenEvent", 0x0040, kSysNtNotImpl},
    {"NtAdjustPrivilegesToken", 0x0041, kSysNtNotImpl},
    {"NtDuplicateToken", 0x0042, kSysNtNotImpl},
    {"NtContinue", 0x0043, kSysNtNotImpl},
    {"NtQueryDefaultUILanguage", 0x0044, kSysNtNotImpl},
    {"NtQueueApcThread", 0x0045, kSysNtNotImpl},
    {"NtYieldExecution", 0x0046, static_cast<u32>(::customos::core::SYS_YIELD)},
    {"NtAddAtom", 0x0047, kSysNtNotImpl},
    {"NtCreateEvent", 0x0048, static_cast<u32>(::customos::core::SYS_EVENT_CREATE)},
    {"NtQueryVolumeInformationFile", 0x0049, kSysNtNotImpl},
    {"NtCreateSection", 0x004a, kSysNtNotImpl},
    {"NtFlushBuffersFile", 0x004b, kSysNtNotImpl},
    {"NtApphelpCacheControl", 0x004c, kSysNtNotImpl},
    {"NtCreateProcessEx", 0x004d, kSysNtNotImpl},
    {"NtCreateThread", 0x004e, kSysNtNotImpl},
    {"NtIsProcessInJob", 0x004f, kSysNtNotImpl},
    {"NtProtectVirtualMemory", 0x0050, kSysNtNotImpl},
    {"NtQuerySection", 0x0051, kSysNtNotImpl},
    {"NtResumeThread", 0x0052, kSysNtNotImpl},
    {"NtTerminateThread", 0x0053, kSysNtNotImpl},
    {"NtReadRequestData", 0x0054, kSysNtNotImpl},
    {"NtCreateFile", 0x0055, static_cast<u32>(::customos::core::SYS_FILE_OPEN)},
    {"NtQueryEvent", 0x0056, kSysNtNotImpl},
    {"NtWriteRequestData", 0x0057, kSysNtNotImpl},
    {"NtOpenDirectoryObject", 0x0058, kSysNtNotImpl},
    {"NtAccessCheckByTypeAndAuditAlarm", 0x0059, kSysNtNotImpl},
    {"NtQuerySystemTime", 0x005a, static_cast<u32>(::customos::core::SYS_GETTIME_FT)},
    {"NtWaitForMultipleObjects", 0x005b, kSysNtNotImpl},
    {"NtSetInformationObject", 0x005c, kSysNtNotImpl},
    {"NtCancelIoFile", 0x005d, kSysNtNotImpl},
    {"NtTraceEvent", 0x005e, kSysNtNotImpl},
    {"NtPowerInformation", 0x005f, kSysNtNotImpl},
    {"NtSetValueKey", 0x0060, kSysNtNotImpl},
    {"NtCancelTimer", 0x0061, kSysNtNotImpl},
    {"NtSetTimer", 0x0062, kSysNtNotImpl},
    {"NtAccessCheckByType", 0x0063, kSysNtNotImpl},
    {"NtAccessCheckByTypeResultList", 0x0064, kSysNtNotImpl},
    {"NtAccessCheckByTypeResultListAndAuditAlarm", 0x0065, kSysNtNotImpl},
    {"NtAccessCheckByTypeResultListAndAuditAlarmByHandle", 0x0066, kSysNtNotImpl},
    {"NtAddBootEntry", 0x006a, kSysNtNotImpl},
    {"NtAddDriverEntry", 0x006b, kSysNtNotImpl},
    {"NtAdjustGroupsToken", 0x006c, kSysNtNotImpl},
    {"NtAlertResumeThread", 0x006f, kSysNtNotImpl},
    {"NtAlertThread", 0x0070, kSysNtNotImpl},
    {"NtAllocateLocallyUniqueId", 0x0073, kSysNtNotImpl},
    {"NtAllocateUserPhysicalPages", 0x0075, kSysNtNotImpl},
    {"NtAllocateUuids", 0x0077, kSysNtNotImpl},
    {"NtAreMappedFilesTheSame", 0x0090, kSysNtNotImpl},
    {"NtAssignProcessToJobObject", 0x0091, kSysNtNotImpl},
    {"NtCompactKeys", 0x009e, kSysNtNotImpl},
    {"NtCompareTokens", 0x00a1, kSysNtNotImpl},
    {"NtCompleteConnectPort", 0x00a2, kSysNtNotImpl},
    {"NtCompressKey", 0x00a3, kSysNtNotImpl},
    {"NtConnectPort", 0x00a4, kSysNtNotImpl},
    {"NtCreateDebugObject", 0x00ab, kSysNtNotImpl},
    {"NtCreateDirectoryObject", 0x00ac, kSysNtNotImpl},
    {"NtCreateEventPair", 0x00b0, kSysNtNotImpl},
    {"NtCreateIoCompletion", 0x00b2, kSysNtNotImpl},
    {"NtCreateJobObject", 0x00b4, kSysNtNotImpl},
    {"NtCreateJobSet", 0x00b5, kSysNtNotImpl},
    {"NtCreateKeyedEvent", 0x00b7, kSysNtNotImpl},
    {"NtCreateMailslotFile", 0x00b9, kSysNtNotImpl},
    {"NtCreateMutant", 0x00ba, static_cast<u32>(::customos::core::SYS_MUTEX_CREATE)},
    {"NtCreateNamedPipeFile", 0x00bb, kSysNtNotImpl},
    {"NtCreatePagingFile", 0x00bc, kSysNtNotImpl},
    {"NtCreatePort", 0x00be, kSysNtNotImpl},
    {"NtCreateProcess", 0x00c0, kSysNtNotImpl},
    {"NtCreateProfile", 0x00c2, kSysNtNotImpl},
    {"NtCreateSemaphore", 0x00c7, kSysNtNotImpl},
    {"NtCreateSymbolicLinkObject", 0x00c8, kSysNtNotImpl},
    {"NtCreateTimer", 0x00cb, kSysNtNotImpl},
    {"NtCreateToken", 0x00cd, kSysNtNotImpl},
    {"NtCreateWaitablePort", 0x00d3, kSysNtNotImpl},
    {"NtDebugActiveProcess", 0x00d6, kSysNtNotImpl},
    {"NtDebugContinue", 0x00d7, kSysNtNotImpl},
    {"NtDeleteAtom", 0x00d8, kSysNtNotImpl},
    {"NtDeleteBootEntry", 0x00d9, kSysNtNotImpl},
    {"NtDeleteDriverEntry", 0x00da, kSysNtNotImpl},
    {"NtDeleteFile", 0x00db, kSysNtNotImpl},
    {"NtDeleteKey", 0x00dc, kSysNtNotImpl},
    {"NtDeleteObjectAuditAlarm", 0x00dd, kSysNtNotImpl},
    {"NtDeleteValueKey", 0x00df, kSysNtNotImpl},
    {"NtDisplayString", 0x00e4, kSysNtNotImpl},
    {"NtEnumerateBootEntries", 0x00e7, kSysNtNotImpl},
    {"NtEnumerateDriverEntries", 0x00e8, kSysNtNotImpl},
    {"NtEnumerateSystemEnvironmentValuesEx", 0x00e9, kSysNtNotImpl},
    {"NtExtendSection", 0x00eb, kSysNtNotImpl},
    {"NtFilterToken", 0x00ed, kSysNtNotImpl},
    {"NtFlushInstructionCache", 0x00f1, kSysNtNotImpl},
    {"NtFlushKey", 0x00f2, kSysNtNotImpl},
    {"NtFlushVirtualMemory", 0x00f4, kSysNtNotImpl},
    {"NtFlushWriteBuffer", 0x00f5, kSysNtNotImpl},
    {"NtFreeUserPhysicalPages", 0x00f6, kSysNtNotImpl},
    {"NtGetContextThread", 0x00fb, kSysNtNotImpl},
    {"NtGetCurrentProcessorNumber", 0x00fc, kSysNtNotImpl},
    {"NtGetDevicePowerState", 0x00fe, kSysNtNotImpl},
    {"NtGetWriteWatch", 0x0104, kSysNtNotImpl},
    {"NtImpersonateAnonymousToken", 0x0105, kSysNtNotImpl},
    {"NtImpersonateThread", 0x0106, kSysNtNotImpl},
    {"NtInitializeRegistry", 0x0109, kSysNtNotImpl},
    {"NtInitiatePowerAction", 0x010a, kSysNtNotImpl},
    {"NtIsSystemResumeAutomatic", 0x010b, kSysNtNotImpl},
    {"NtListenPort", 0x010d, kSysNtNotImpl},
    {"NtLoadDriver", 0x010e, kSysNtNotImpl},
    {"NtLoadKey", 0x0110, kSysNtNotImpl},
    {"NtLoadKey2", 0x0111, kSysNtNotImpl},
    {"NtLoadKeyEx", 0x0113, kSysNtNotImpl},
    {"NtLockFile", 0x0114, kSysNtNotImpl},
    {"NtLockProductActivationKeys", 0x0115, kSysNtNotImpl},
    {"NtLockRegistryKey", 0x0116, kSysNtNotImpl},
    {"NtLockVirtualMemory", 0x0117, kSysNtNotImpl},
    {"NtMakePermanentObject", 0x0118, kSysNtNotImpl},
    {"NtMakeTemporaryObject", 0x0119, kSysNtNotImpl},
    {"NtMapUserPhysicalPages", 0x011d, kSysNtNotImpl},
    {"NtModifyBootEntry", 0x011f, kSysNtNotImpl},
    {"NtModifyDriverEntry", 0x0120, kSysNtNotImpl},
    {"NtNotifyChangeDirectoryFile", 0x0121, kSysNtNotImpl},
    {"NtNotifyChangeKey", 0x0123, kSysNtNotImpl},
    {"NtNotifyChangeMultipleKeys", 0x0124, kSysNtNotImpl},
    {"NtOpenEventPair", 0x0128, kSysNtNotImpl},
    {"NtOpenIoCompletion", 0x0129, kSysNtNotImpl},
    {"NtOpenJobObject", 0x012a, kSysNtNotImpl},
    {"NtOpenKeyedEvent", 0x012e, kSysNtNotImpl},
    {"NtOpenMutant", 0x012f, kSysNtNotImpl},
    {"NtOpenObjectAuditAlarm", 0x0130, kSysNtNotImpl},
    {"NtOpenProcessToken", 0x0133, kSysNtNotImpl},
    {"NtOpenSemaphore", 0x0136, kSysNtNotImpl},
    {"NtOpenSymbolicLinkObject", 0x0138, kSysNtNotImpl},
    {"NtOpenThread", 0x0139, kSysNtNotImpl},
    {"NtOpenTimer", 0x013a, kSysNtNotImpl},
    {"NtPlugPlayControl", 0x013d, kSysNtNotImpl},
    {"NtPrivilegeCheck", 0x0142, kSysNtNotImpl},
    {"NtPrivilegeObjectAuditAlarm", 0x0143, kSysNtNotImpl},
    {"NtPrivilegedServiceAuditAlarm", 0x0144, kSysNtNotImpl},
    {"NtPulseEvent", 0x0148, kSysNtNotImpl},
    {"NtQueryBootEntryOrder", 0x014a, kSysNtNotImpl},
    {"NtQueryBootOptions", 0x014b, kSysNtNotImpl},
    {"NtQueryDebugFilterState", 0x014c, kSysNtNotImpl},
    {"NtQueryDirectoryObject", 0x014e, kSysNtNotImpl},
    {"NtQueryDriverEntryOrder", 0x014f, kSysNtNotImpl},
    {"NtQueryEaFile", 0x0150, kSysNtNotImpl},
    {"NtQueryFullAttributesFile", 0x0151, kSysNtNotImpl},
    {"NtQueryInformationAtom", 0x0152, kSysNtNotImpl},
    {"NtQueryInformationJobObject", 0x0156, kSysNtNotImpl},
    {"NtQueryInformationPort", 0x0157, kSysNtNotImpl},
    {"NtQueryInstallUILanguage", 0x015c, kSysNtNotImpl},
    {"NtQueryIntervalProfile", 0x015d, kSysNtNotImpl},
    {"NtQueryIoCompletion", 0x015e, kSysNtNotImpl},
    {"NtQueryMultipleValueKey", 0x0161, kSysNtNotImpl},
    {"NtQueryMutant", 0x0162, kSysNtNotImpl},
    {"NtQueryOpenSubKeys", 0x0163, kSysNtNotImpl},
    {"NtQueryOpenSubKeysEx", 0x0164, kSysNtNotImpl},
    {"NtQueryPortInformationProcess", 0x0165, kSysNtNotImpl},
    {"NtQueryQuotaInformationFile", 0x0166, kSysNtNotImpl},
    {"NtQuerySecurityObject", 0x0168, kSysNtNotImpl},
    {"NtQuerySemaphore", 0x016a, kSysNtNotImpl},
    {"NtQuerySymbolicLinkObject", 0x016b, kSysNtNotImpl},
    {"NtQuerySystemEnvironmentValue", 0x016c, kSysNtNotImpl},
    {"NtQuerySystemEnvironmentValueEx", 0x016d, kSysNtNotImpl},
    {"NtQueryTimerResolution", 0x016f, kSysNtNotImpl},
    {"NtRaiseException", 0x0174, kSysNtNotImpl},
    {"NtRaiseHardError", 0x0175, kSysNtNotImpl},
    {"NtRegisterThreadTerminatePort", 0x017c, kSysNtNotImpl},
    {"NtReleaseKeyedEvent", 0x017d, kSysNtNotImpl},
    {"NtRemoveProcessDebug", 0x0180, kSysNtNotImpl},
    {"NtRenameKey", 0x0181, kSysNtNotImpl},
    {"NtReplaceKey", 0x0183, kSysNtNotImpl},
    {"NtReplyWaitReplyPort", 0x0185, kSysNtNotImpl},
    {"NtRequestPort", 0x0186, kSysNtNotImpl},
    {"NtResetEvent", 0x0187, static_cast<u32>(::customos::core::SYS_EVENT_RESET)},
    {"NtResetWriteWatch", 0x0188, kSysNtNotImpl},
    {"NtRestoreKey", 0x0189, kSysNtNotImpl},
    {"NtResumeProcess", 0x018a, kSysNtNotImpl},
    {"NtSaveKey", 0x0191, kSysNtNotImpl},
    {"NtSaveKeyEx", 0x0192, kSysNtNotImpl},
    {"NtSaveMergedKeys", 0x0193, kSysNtNotImpl},
    {"NtSecureConnectPort", 0x0194, kSysNtNotImpl},
    {"NtSetBootEntryOrder", 0x0196, kSysNtNotImpl},
    {"NtSetBootOptions", 0x0197, kSysNtNotImpl},
    {"NtSetContextThread", 0x019a, kSysNtNotImpl},
    {"NtSetDebugFilterState", 0x019b, kSysNtNotImpl},
    {"NtSetDefaultHardErrorPort", 0x019c, kSysNtNotImpl},
    {"NtSetDefaultLocale", 0x019d, kSysNtNotImpl},
    {"NtSetDefaultUILanguage", 0x019e, kSysNtNotImpl},
    {"NtSetDriverEntryOrder", 0x019f, kSysNtNotImpl},
    {"NtSetEaFile", 0x01a0, kSysNtNotImpl},
    {"NtSetHighEventPair", 0x01a2, kSysNtNotImpl},
    {"NtSetHighWaitLowEventPair", 0x01a3, kSysNtNotImpl},
    {"NtSetInformationDebugObject", 0x01a6, kSysNtNotImpl},
    {"NtSetInformationJobObject", 0x01a9, kSysNtNotImpl},
    {"NtSetInformationKey", 0x01aa, kSysNtNotImpl},
    {"NtSetInformationToken", 0x01ad, kSysNtNotImpl},
    {"NtSetIntervalProfile", 0x01b2, kSysNtNotImpl},
    {"NtSetIoCompletion", 0x01b3, kSysNtNotImpl},
    {"NtSetLdtEntries", 0x01b5, kSysNtNotImpl},
    {"NtSetLowEventPair", 0x01b6, kSysNtNotImpl},
    {"NtSetLowWaitHighEventPair", 0x01b7, kSysNtNotImpl},
    {"NtSetQuotaInformationFile", 0x01b8, kSysNtNotImpl},
    {"NtSetSecurityObject", 0x01b9, kSysNtNotImpl},
    {"NtSetSystemEnvironmentValue", 0x01ba, kSysNtNotImpl},
    {"NtSetSystemEnvironmentValueEx", 0x01bb, kSysNtNotImpl},
    {"NtSetSystemInformation", 0x01bc, kSysNtNotImpl},
    {"NtSetSystemPowerState", 0x01bd, kSysNtNotImpl},
    {"NtSetSystemTime", 0x01be, kSysNtNotImpl},
    {"NtSetThreadExecutionState", 0x01bf, kSysNtNotImpl},
    {"NtSetTimerResolution", 0x01c2, kSysNtNotImpl},
    {"NtSetUuidSeed", 0x01c3, kSysNtNotImpl},
    {"NtSetVolumeInformationFile", 0x01c4, kSysNtNotImpl},
    {"NtShutdownSystem", 0x01c6, kSysNtNotImpl},
    {"NtSignalAndWaitForSingleObject", 0x01c8, kSysNtNotImpl},
    {"NtStartProfile", 0x01ca, kSysNtNotImpl},
    {"NtStopProfile", 0x01cb, kSysNtNotImpl},
    {"NtSuspendProcess", 0x01ce, kSysNtNotImpl},
    {"NtSuspendThread", 0x01cf, kSysNtNotImpl},
    {"NtSystemDebugControl", 0x01d0, kSysNtNotImpl},
    {"NtTerminateJobObject", 0x01d2, kSysNtNotImpl},
    {"NtTestAlert", 0x01d3, kSysNtNotImpl},
    {"NtTranslateFilePath", 0x01d7, kSysNtNotImpl},
    {"NtUnloadDriver", 0x01d9, kSysNtNotImpl},
    {"NtUnloadKey", 0x01da, kSysNtNotImpl},
    {"NtUnloadKey2", 0x01db, kSysNtNotImpl},
    {"NtUnloadKeyEx", 0x01dc, kSysNtNotImpl},
    {"NtUnlockFile", 0x01dd, kSysNtNotImpl},
    {"NtUnlockVirtualMemory", 0x01de, kSysNtNotImpl},
    {"NtVdmControl", 0x01e2, kSysNtNotImpl},
    {"NtWaitForDebugEvent", 0x01e4, kSysNtNotImpl},
    {"NtWaitForKeyedEvent", 0x01e5, kSysNtNotImpl},
    {"NtWaitHighEventPair", 0x01e7, kSysNtNotImpl},
    {"NtWaitLowEventPair", 0x01e8, kSysNtNotImpl},
};

inline constexpr u32 kBedrockNtSyscallCount =
    sizeof(kBedrockNtSyscalls) / sizeof(kBedrockNtSyscalls[0]);

inline constexpr u32 kBedrockNtSyscallsCovered = 19;

} // namespace customos::subsystems::win32
