// AUTO-GENERATED — do not edit by hand.
// Regenerate via: python3 tools/linux-compat/gen-linux-syscall-table.py
//                 --csv tools/linux-compat/linux-syscalls-x86_64.csv
//                 --mapped-from-dispatcher kernel/subsystems/linux/syscall.cpp
//                 --out kernel/subsystems/linux/linux_syscall_table_generated.h
//
// Source data: tools/linux-compat/linux-syscalls-x86_64.csv
// Total syscalls listed: 374
// Handlers implemented in kernel/subsystems/linux/syscall.cpp: 69
// Coverage: 18%
//
// See tools/linux-compat/README.md for provenance.

#pragma once

#include "../../core/types.h"

namespace customos::subsystems::linux
{

enum class HandlerState : u8
{
    Unknown = 0,     // number outside the known ABI range
    Unimplemented,   // known name, no Do* in syscall.cpp
    Implemented,     // known name, matching Do* handler exists
};

struct LinuxSyscallEntry
{
    u16 number;
    u8 args;            // 0..6
    HandlerState state;
    const char* name;
};

/// Dense-by-number, sorted table of every known x86_64 Linux
/// syscall. Linear scan for now; the table is small (< 500) and
/// every miss walks it exactly once per failed syscall.
inline constexpr LinuxSyscallEntry kLinuxSyscalls[] = {
    {0, 3, HandlerState::Implemented, "read"},
    {1, 3, HandlerState::Implemented, "write"},
    {2, 3, HandlerState::Implemented, "open"},
    {3, 1, HandlerState::Implemented, "close"},
    {4, 2, HandlerState::Implemented, "stat"},
    {5, 2, HandlerState::Implemented, "fstat"},
    {6, 2, HandlerState::Unimplemented, "lstat"},
    {7, 3, HandlerState::Implemented, "poll"},
    {8, 3, HandlerState::Implemented, "lseek"},
    {9, 6, HandlerState::Implemented, "mmap"},
    {10, 3, HandlerState::Implemented, "mprotect"},
    {11, 2, HandlerState::Implemented, "munmap"},
    {12, 1, HandlerState::Implemented, "brk"},
    {13, 4, HandlerState::Implemented, "rt_sigaction"},
    {14, 4, HandlerState::Implemented, "rt_sigprocmask"},
    {15, 0, HandlerState::Implemented, "rt_sigreturn"},
    {16, 3, HandlerState::Implemented, "ioctl"},
    {17, 4, HandlerState::Implemented, "pread64"},
    {18, 4, HandlerState::Implemented, "pwrite64"},
    {19, 3, HandlerState::Implemented, "readv"},
    {20, 3, HandlerState::Implemented, "writev"},
    {21, 2, HandlerState::Implemented, "access"},
    {22, 1, HandlerState::Unimplemented, "pipe"},
    {23, 5, HandlerState::Implemented, "select"},
    {24, 0, HandlerState::Implemented, "sched_yield"},
    {25, 5, HandlerState::Unimplemented, "mremap"},
    {26, 3, HandlerState::Unimplemented, "msync"},
    {27, 3, HandlerState::Unimplemented, "mincore"},
    {28, 3, HandlerState::Implemented, "madvise"},
    {29, 3, HandlerState::Unimplemented, "shmget"},
    {30, 3, HandlerState::Unimplemented, "shmat"},
    {31, 3, HandlerState::Unimplemented, "shmctl"},
    {32, 1, HandlerState::Implemented, "dup"},
    {33, 2, HandlerState::Implemented, "dup2"},
    {34, 0, HandlerState::Unimplemented, "pause"},
    {35, 2, HandlerState::Implemented, "nanosleep"},
    {36, 2, HandlerState::Unimplemented, "getitimer"},
    {37, 1, HandlerState::Unimplemented, "alarm"},
    {38, 3, HandlerState::Unimplemented, "setitimer"},
    {39, 0, HandlerState::Implemented, "getpid"},
    {40, 4, HandlerState::Unimplemented, "sendfile"},
    {41, 3, HandlerState::Unimplemented, "socket"},
    {42, 3, HandlerState::Unimplemented, "connect"},
    {43, 3, HandlerState::Unimplemented, "accept"},
    {44, 6, HandlerState::Unimplemented, "sendto"},
    {45, 6, HandlerState::Unimplemented, "recvfrom"},
    {46, 3, HandlerState::Unimplemented, "sendmsg"},
    {47, 3, HandlerState::Unimplemented, "recvmsg"},
    {48, 2, HandlerState::Unimplemented, "shutdown"},
    {49, 3, HandlerState::Unimplemented, "bind"},
    {50, 2, HandlerState::Unimplemented, "listen"},
    {51, 3, HandlerState::Unimplemented, "getsockname"},
    {52, 3, HandlerState::Unimplemented, "getpeername"},
    {53, 4, HandlerState::Unimplemented, "socketpair"},
    {54, 5, HandlerState::Unimplemented, "setsockopt"},
    {55, 5, HandlerState::Unimplemented, "getsockopt"},
    {56, 5, HandlerState::Unimplemented, "clone"},
    {57, 0, HandlerState::Unimplemented, "fork"},
    {58, 0, HandlerState::Unimplemented, "vfork"},
    {59, 3, HandlerState::Unimplemented, "execve"},
    {60, 1, HandlerState::Implemented, "exit"},
    {61, 4, HandlerState::Unimplemented, "wait4"},
    {62, 2, HandlerState::Implemented, "kill"},
    {63, 1, HandlerState::Implemented, "uname"},
    {64, 3, HandlerState::Unimplemented, "semget"},
    {65, 3, HandlerState::Unimplemented, "semop"},
    {66, 4, HandlerState::Unimplemented, "semctl"},
    {67, 1, HandlerState::Unimplemented, "shmdt"},
    {68, 2, HandlerState::Unimplemented, "msgget"},
    {69, 4, HandlerState::Unimplemented, "msgsnd"},
    {70, 5, HandlerState::Unimplemented, "msgrcv"},
    {71, 3, HandlerState::Unimplemented, "msgctl"},
    {72, 3, HandlerState::Implemented, "fcntl"},
    {73, 2, HandlerState::Unimplemented, "flock"},
    {74, 1, HandlerState::Implemented, "fsync"},
    {75, 1, HandlerState::Implemented, "fdatasync"},
    {76, 2, HandlerState::Unimplemented, "truncate"},
    {77, 2, HandlerState::Unimplemented, "ftruncate"},
    {78, 3, HandlerState::Unimplemented, "getdents"},
    {79, 2, HandlerState::Implemented, "getcwd"},
    {80, 1, HandlerState::Implemented, "chdir"},
    {81, 1, HandlerState::Implemented, "fchdir"},
    {82, 2, HandlerState::Unimplemented, "rename"},
    {83, 2, HandlerState::Unimplemented, "mkdir"},
    {84, 1, HandlerState::Unimplemented, "rmdir"},
    {85, 2, HandlerState::Unimplemented, "creat"},
    {86, 2, HandlerState::Unimplemented, "link"},
    {87, 1, HandlerState::Unimplemented, "unlink"},
    {88, 2, HandlerState::Unimplemented, "symlink"},
    {89, 3, HandlerState::Implemented, "readlink"},
    {90, 2, HandlerState::Unimplemented, "chmod"},
    {91, 2, HandlerState::Unimplemented, "fchmod"},
    {92, 3, HandlerState::Unimplemented, "chown"},
    {93, 3, HandlerState::Unimplemented, "fchown"},
    {94, 3, HandlerState::Unimplemented, "lchown"},
    {95, 1, HandlerState::Unimplemented, "umask"},
    {96, 2, HandlerState::Implemented, "gettimeofday"},
    {97, 2, HandlerState::Implemented, "getrlimit"},
    {98, 2, HandlerState::Implemented, "getrusage"},
    {99, 1, HandlerState::Implemented, "sysinfo"},
    {100, 1, HandlerState::Unimplemented, "times"},
    {101, 4, HandlerState::Unimplemented, "ptrace"},
    {102, 0, HandlerState::Implemented, "getuid"},
    {103, 3, HandlerState::Unimplemented, "syslog"},
    {104, 0, HandlerState::Implemented, "getgid"},
    {105, 1, HandlerState::Unimplemented, "setuid"},
    {106, 1, HandlerState::Unimplemented, "setgid"},
    {107, 0, HandlerState::Implemented, "geteuid"},
    {108, 0, HandlerState::Implemented, "getegid"},
    {109, 2, HandlerState::Implemented, "setpgid"},
    {110, 0, HandlerState::Implemented, "getppid"},
    {111, 0, HandlerState::Implemented, "getpgrp"},
    {112, 0, HandlerState::Unimplemented, "setsid"},
    {113, 2, HandlerState::Unimplemented, "setreuid"},
    {114, 2, HandlerState::Unimplemented, "setregid"},
    {115, 2, HandlerState::Unimplemented, "getgroups"},
    {116, 2, HandlerState::Unimplemented, "setgroups"},
    {117, 3, HandlerState::Unimplemented, "setresuid"},
    {118, 3, HandlerState::Unimplemented, "getresuid"},
    {119, 3, HandlerState::Unimplemented, "setresgid"},
    {120, 3, HandlerState::Unimplemented, "getresgid"},
    {121, 1, HandlerState::Implemented, "getpgid"},
    {122, 1, HandlerState::Unimplemented, "setfsuid"},
    {123, 1, HandlerState::Unimplemented, "setfsgid"},
    {124, 1, HandlerState::Implemented, "getsid"},
    {125, 2, HandlerState::Unimplemented, "capget"},
    {126, 2, HandlerState::Unimplemented, "capset"},
    {127, 2, HandlerState::Unimplemented, "rt_sigpending"},
    {128, 4, HandlerState::Unimplemented, "rt_sigtimedwait"},
    {129, 3, HandlerState::Unimplemented, "rt_sigqueueinfo"},
    {130, 2, HandlerState::Unimplemented, "rt_sigsuspend"},
    {131, 2, HandlerState::Implemented, "sigaltstack"},
    {132, 2, HandlerState::Unimplemented, "utime"},
    {133, 3, HandlerState::Unimplemented, "mknod"},
    {134, 1, HandlerState::Unimplemented, "uselib"},
    {135, 1, HandlerState::Unimplemented, "personality"},
    {136, 2, HandlerState::Unimplemented, "ustat"},
    {137, 2, HandlerState::Unimplemented, "statfs"},
    {138, 2, HandlerState::Unimplemented, "fstatfs"},
    {139, 3, HandlerState::Unimplemented, "sysfs"},
    {140, 2, HandlerState::Unimplemented, "getpriority"},
    {141, 3, HandlerState::Unimplemented, "setpriority"},
    {142, 2, HandlerState::Unimplemented, "sched_setparam"},
    {143, 2, HandlerState::Unimplemented, "sched_getparam"},
    {144, 3, HandlerState::Unimplemented, "sched_setscheduler"},
    {145, 1, HandlerState::Unimplemented, "sched_getscheduler"},
    {146, 1, HandlerState::Unimplemented, "sched_get_priority_max"},
    {147, 1, HandlerState::Unimplemented, "sched_get_priority_min"},
    {148, 2, HandlerState::Unimplemented, "sched_rr_get_interval"},
    {149, 2, HandlerState::Unimplemented, "mlock"},
    {150, 2, HandlerState::Unimplemented, "munlock"},
    {151, 1, HandlerState::Unimplemented, "mlockall"},
    {152, 0, HandlerState::Unimplemented, "munlockall"},
    {153, 0, HandlerState::Unimplemented, "vhangup"},
    {154, 3, HandlerState::Unimplemented, "modify_ldt"},
    {155, 2, HandlerState::Unimplemented, "pivot_root"},
    {156, 1, HandlerState::Unimplemented, "_sysctl"},
    {157, 5, HandlerState::Unimplemented, "prctl"},
    {158, 2, HandlerState::Implemented, "arch_prctl"},
    {159, 1, HandlerState::Unimplemented, "adjtimex"},
    {160, 2, HandlerState::Implemented, "setrlimit"},
    {161, 1, HandlerState::Unimplemented, "chroot"},
    {162, 0, HandlerState::Unimplemented, "sync"},
    {163, 1, HandlerState::Unimplemented, "acct"},
    {164, 2, HandlerState::Unimplemented, "settimeofday"},
    {165, 5, HandlerState::Unimplemented, "mount"},
    {166, 2, HandlerState::Unimplemented, "umount2"},
    {167, 2, HandlerState::Unimplemented, "swapon"},
    {168, 1, HandlerState::Unimplemented, "swapoff"},
    {169, 4, HandlerState::Unimplemented, "reboot"},
    {170, 2, HandlerState::Unimplemented, "sethostname"},
    {171, 2, HandlerState::Unimplemented, "setdomainname"},
    {172, 1, HandlerState::Unimplemented, "iopl"},
    {173, 3, HandlerState::Unimplemented, "ioperm"},
    {174, 0, HandlerState::Unimplemented, "create_module"},
    {175, 3, HandlerState::Unimplemented, "init_module"},
    {176, 2, HandlerState::Unimplemented, "delete_module"},
    {177, 0, HandlerState::Unimplemented, "get_kernel_syms"},
    {178, 0, HandlerState::Unimplemented, "query_module"},
    {179, 4, HandlerState::Unimplemented, "quotactl"},
    {180, 0, HandlerState::Unimplemented, "nfsservctl"},
    {181, 0, HandlerState::Unimplemented, "getpmsg"},
    {182, 0, HandlerState::Unimplemented, "putpmsg"},
    {183, 0, HandlerState::Unimplemented, "afs_syscall"},
    {184, 0, HandlerState::Unimplemented, "tuxcall"},
    {185, 0, HandlerState::Unimplemented, "security"},
    {186, 0, HandlerState::Implemented, "gettid"},
    {187, 3, HandlerState::Unimplemented, "readahead"},
    {188, 5, HandlerState::Unimplemented, "setxattr"},
    {189, 5, HandlerState::Unimplemented, "lsetxattr"},
    {190, 5, HandlerState::Unimplemented, "fsetxattr"},
    {191, 4, HandlerState::Unimplemented, "getxattr"},
    {192, 4, HandlerState::Unimplemented, "lgetxattr"},
    {193, 4, HandlerState::Unimplemented, "fgetxattr"},
    {194, 3, HandlerState::Unimplemented, "listxattr"},
    {195, 3, HandlerState::Unimplemented, "llistxattr"},
    {196, 3, HandlerState::Unimplemented, "flistxattr"},
    {197, 2, HandlerState::Unimplemented, "removexattr"},
    {198, 2, HandlerState::Unimplemented, "lremovexattr"},
    {199, 2, HandlerState::Unimplemented, "fremovexattr"},
    {200, 2, HandlerState::Unimplemented, "tkill"},
    {201, 1, HandlerState::Implemented, "time"},
    {202, 6, HandlerState::Implemented, "futex"},
    {203, 3, HandlerState::Unimplemented, "sched_setaffinity"},
    {204, 3, HandlerState::Unimplemented, "sched_getaffinity"},
    {205, 1, HandlerState::Unimplemented, "set_thread_area"},
    {206, 2, HandlerState::Unimplemented, "io_setup"},
    {207, 1, HandlerState::Unimplemented, "io_destroy"},
    {208, 4, HandlerState::Unimplemented, "io_getevents"},
    {209, 3, HandlerState::Unimplemented, "io_submit"},
    {210, 3, HandlerState::Unimplemented, "io_cancel"},
    {211, 1, HandlerState::Unimplemented, "get_thread_area"},
    {212, 3, HandlerState::Unimplemented, "lookup_dcookie"},
    {213, 1, HandlerState::Unimplemented, "epoll_create"},
    {214, 0, HandlerState::Unimplemented, "epoll_ctl_old"},
    {215, 0, HandlerState::Unimplemented, "epoll_wait_old"},
    {216, 5, HandlerState::Unimplemented, "remap_file_pages"},
    {217, 3, HandlerState::Implemented, "getdents64"},
    {218, 1, HandlerState::Implemented, "set_tid_address"},
    {219, 0, HandlerState::Unimplemented, "restart_syscall"},
    {220, 4, HandlerState::Unimplemented, "semtimedop"},
    {221, 4, HandlerState::Unimplemented, "fadvise64"},
    {222, 3, HandlerState::Unimplemented, "timer_create"},
    {223, 4, HandlerState::Unimplemented, "timer_settime"},
    {224, 2, HandlerState::Unimplemented, "timer_gettime"},
    {225, 1, HandlerState::Unimplemented, "timer_getoverrun"},
    {226, 1, HandlerState::Unimplemented, "timer_delete"},
    {227, 2, HandlerState::Unimplemented, "clock_settime"},
    {228, 2, HandlerState::Implemented, "clock_gettime"},
    {229, 2, HandlerState::Unimplemented, "clock_getres"},
    {230, 4, HandlerState::Unimplemented, "clock_nanosleep"},
    {231, 1, HandlerState::Implemented, "exit_group"},
    {232, 4, HandlerState::Unimplemented, "epoll_wait"},
    {233, 4, HandlerState::Unimplemented, "epoll_ctl"},
    {234, 3, HandlerState::Implemented, "tgkill"},
    {235, 2, HandlerState::Unimplemented, "utimes"},
    {236, 0, HandlerState::Unimplemented, "vserver"},
    {237, 6, HandlerState::Unimplemented, "mbind"},
    {238, 3, HandlerState::Unimplemented, "set_mempolicy"},
    {239, 5, HandlerState::Unimplemented, "get_mempolicy"},
    {240, 4, HandlerState::Unimplemented, "mq_open"},
    {241, 1, HandlerState::Unimplemented, "mq_unlink"},
    {242, 5, HandlerState::Unimplemented, "mq_timedsend"},
    {243, 5, HandlerState::Unimplemented, "mq_timedreceive"},
    {244, 2, HandlerState::Unimplemented, "mq_notify"},
    {245, 3, HandlerState::Unimplemented, "mq_getsetattr"},
    {246, 4, HandlerState::Unimplemented, "kexec_load"},
    {247, 5, HandlerState::Unimplemented, "waitid"},
    {248, 5, HandlerState::Unimplemented, "add_key"},
    {249, 4, HandlerState::Unimplemented, "request_key"},
    {250, 5, HandlerState::Unimplemented, "keyctl"},
    {251, 3, HandlerState::Unimplemented, "ioprio_set"},
    {252, 2, HandlerState::Unimplemented, "ioprio_get"},
    {253, 0, HandlerState::Unimplemented, "inotify_init"},
    {254, 3, HandlerState::Unimplemented, "inotify_add_watch"},
    {255, 2, HandlerState::Unimplemented, "inotify_rm_watch"},
    {256, 4, HandlerState::Unimplemented, "migrate_pages"},
    {257, 4, HandlerState::Implemented, "openat"},
    {258, 3, HandlerState::Unimplemented, "mkdirat"},
    {259, 4, HandlerState::Unimplemented, "mknodat"},
    {260, 5, HandlerState::Unimplemented, "fchownat"},
    {261, 3, HandlerState::Unimplemented, "futimesat"},
    {262, 4, HandlerState::Implemented, "newfstatat"},
    {263, 3, HandlerState::Unimplemented, "unlinkat"},
    {264, 4, HandlerState::Unimplemented, "renameat"},
    {265, 5, HandlerState::Unimplemented, "linkat"},
    {266, 3, HandlerState::Unimplemented, "symlinkat"},
    {267, 4, HandlerState::Unimplemented, "readlinkat"},
    {268, 3, HandlerState::Unimplemented, "fchmodat"},
    {269, 3, HandlerState::Unimplemented, "faccessat"},
    {270, 6, HandlerState::Unimplemented, "pselect6"},
    {271, 5, HandlerState::Unimplemented, "ppoll"},
    {272, 1, HandlerState::Unimplemented, "unshare"},
    {273, 2, HandlerState::Implemented, "set_robust_list"},
    {274, 3, HandlerState::Implemented, "get_robust_list"},
    {275, 6, HandlerState::Unimplemented, "splice"},
    {276, 4, HandlerState::Unimplemented, "tee"},
    {277, 4, HandlerState::Unimplemented, "sync_file_range"},
    {278, 4, HandlerState::Unimplemented, "vmsplice"},
    {279, 6, HandlerState::Unimplemented, "move_pages"},
    {280, 4, HandlerState::Unimplemented, "utimensat"},
    {281, 6, HandlerState::Unimplemented, "epoll_pwait"},
    {282, 3, HandlerState::Unimplemented, "signalfd"},
    {283, 2, HandlerState::Unimplemented, "timerfd_create"},
    {284, 1, HandlerState::Unimplemented, "eventfd"},
    {285, 4, HandlerState::Unimplemented, "fallocate"},
    {286, 4, HandlerState::Unimplemented, "timerfd_settime"},
    {287, 2, HandlerState::Unimplemented, "timerfd_gettime"},
    {288, 4, HandlerState::Unimplemented, "accept4"},
    {289, 4, HandlerState::Unimplemented, "signalfd4"},
    {290, 2, HandlerState::Unimplemented, "eventfd2"},
    {291, 1, HandlerState::Unimplemented, "epoll_create1"},
    {292, 3, HandlerState::Implemented, "dup3"},
    {293, 2, HandlerState::Unimplemented, "pipe2"},
    {294, 1, HandlerState::Unimplemented, "inotify_init1"},
    {295, 5, HandlerState::Unimplemented, "preadv"},
    {296, 5, HandlerState::Unimplemented, "pwritev"},
    {297, 4, HandlerState::Unimplemented, "rt_tgsigqueueinfo"},
    {298, 5, HandlerState::Unimplemented, "perf_event_open"},
    {299, 5, HandlerState::Unimplemented, "recvmmsg"},
    {300, 2, HandlerState::Unimplemented, "fanotify_init"},
    {301, 5, HandlerState::Unimplemented, "fanotify_mark"},
    {302, 4, HandlerState::Implemented, "prlimit64"},
    {303, 5, HandlerState::Unimplemented, "name_to_handle_at"},
    {304, 3, HandlerState::Unimplemented, "open_by_handle_at"},
    {305, 2, HandlerState::Unimplemented, "clock_adjtime"},
    {306, 1, HandlerState::Unimplemented, "syncfs"},
    {307, 4, HandlerState::Unimplemented, "sendmmsg"},
    {308, 2, HandlerState::Unimplemented, "setns"},
    {309, 3, HandlerState::Unimplemented, "getcpu"},
    {310, 6, HandlerState::Unimplemented, "process_vm_readv"},
    {311, 6, HandlerState::Unimplemented, "process_vm_writev"},
    {312, 5, HandlerState::Unimplemented, "kcmp"},
    {313, 3, HandlerState::Unimplemented, "finit_module"},
    {314, 3, HandlerState::Unimplemented, "sched_setattr"},
    {315, 4, HandlerState::Unimplemented, "sched_getattr"},
    {316, 5, HandlerState::Unimplemented, "renameat2"},
    {317, 3, HandlerState::Unimplemented, "seccomp"},
    {318, 3, HandlerState::Implemented, "getrandom"},
    {319, 2, HandlerState::Unimplemented, "memfd_create"},
    {320, 5, HandlerState::Unimplemented, "kexec_file_load"},
    {321, 3, HandlerState::Unimplemented, "bpf"},
    {322, 5, HandlerState::Unimplemented, "execveat"},
    {323, 1, HandlerState::Unimplemented, "userfaultfd"},
    {324, 2, HandlerState::Unimplemented, "membarrier"},
    {325, 3, HandlerState::Unimplemented, "mlock2"},
    {326, 6, HandlerState::Unimplemented, "copy_file_range"},
    {327, 6, HandlerState::Unimplemented, "preadv2"},
    {328, 6, HandlerState::Unimplemented, "pwritev2"},
    {329, 4, HandlerState::Unimplemented, "pkey_mprotect"},
    {330, 2, HandlerState::Unimplemented, "pkey_alloc"},
    {331, 1, HandlerState::Unimplemented, "pkey_free"},
    {332, 5, HandlerState::Unimplemented, "statx"},
    {333, 6, HandlerState::Unimplemented, "io_pgetevents"},
    {334, 4, HandlerState::Unimplemented, "rseq"},
    {424, 4, HandlerState::Unimplemented, "pidfd_send_signal"},
    {425, 2, HandlerState::Unimplemented, "io_uring_setup"},
    {426, 6, HandlerState::Unimplemented, "io_uring_enter"},
    {427, 4, HandlerState::Unimplemented, "io_uring_register"},
    {428, 3, HandlerState::Unimplemented, "open_tree"},
    {429, 5, HandlerState::Unimplemented, "move_mount"},
    {430, 2, HandlerState::Unimplemented, "fsopen"},
    {431, 5, HandlerState::Unimplemented, "fsconfig"},
    {432, 3, HandlerState::Unimplemented, "fsmount"},
    {433, 3, HandlerState::Unimplemented, "fspick"},
    {434, 2, HandlerState::Unimplemented, "pidfd_open"},
    {435, 2, HandlerState::Unimplemented, "clone3"},
    {436, 3, HandlerState::Unimplemented, "close_range"},
    {437, 4, HandlerState::Unimplemented, "openat2"},
    {438, 3, HandlerState::Unimplemented, "pidfd_getfd"},
    {439, 4, HandlerState::Unimplemented, "faccessat2"},
    {440, 5, HandlerState::Unimplemented, "process_madvise"},
    {441, 6, HandlerState::Unimplemented, "epoll_pwait2"},
    {442, 5, HandlerState::Unimplemented, "mount_setattr"},
    {443, 4, HandlerState::Unimplemented, "quotactl_fd"},
    {444, 3, HandlerState::Unimplemented, "landlock_create_ruleset"},
    {445, 4, HandlerState::Unimplemented, "landlock_add_rule"},
    {446, 2, HandlerState::Unimplemented, "landlock_restrict_self"},
    {447, 1, HandlerState::Unimplemented, "memfd_secret"},
    {448, 2, HandlerState::Unimplemented, "process_mrelease"},
    {449, 5, HandlerState::Unimplemented, "futex_waitv"},
    {450, 4, HandlerState::Unimplemented, "set_mempolicy_home_node"},
    {451, 4, HandlerState::Unimplemented, "cachestat"},
    {452, 4, HandlerState::Unimplemented, "fchmodat2"},
    {453, 3, HandlerState::Unimplemented, "map_shadow_stack"},
    {454, 4, HandlerState::Unimplemented, "futex_wake"},
    {455, 6, HandlerState::Unimplemented, "futex_wait"},
    {456, 4, HandlerState::Unimplemented, "futex_requeue"},
    {457, 4, HandlerState::Unimplemented, "statmount"},
    {458, 4, HandlerState::Unimplemented, "listmount"},
    {459, 4, HandlerState::Unimplemented, "lsm_get_self_attr"},
    {460, 4, HandlerState::Unimplemented, "lsm_set_self_attr"},
    {461, 3, HandlerState::Unimplemented, "lsm_list_modules"},
    {462, 3, HandlerState::Unimplemented, "mseal"},
};

inline constexpr u32 kLinuxSyscallCount =
    sizeof(kLinuxSyscalls) / sizeof(kLinuxSyscalls[0]);

inline constexpr u32 kLinuxSyscallHandlersImplemented = 69;

/// Look up `nr` in `kLinuxSyscalls`. Returns nullptr if unknown.
/// Linear scan — callers typically hit this on a miss path, where
/// the log line it's building is orders of magnitude more expensive
/// than the walk.
inline const LinuxSyscallEntry* LinuxSyscallLookup(u64 nr)
{
    for (const auto& e : kLinuxSyscalls)
    {
        if (e.number == nr)
            return &e;
    }
    return nullptr;
}

} // namespace customos::subsystems::linux
