// AUTO-GENERATED — do not edit by hand.
// Regenerate via: python3 tools/linux-compat/gen-linux-syscall-table.py
//                 --csv tools/linux-compat/linux-syscalls-x86_64.csv
//                 --mapped-from-dispatcher kernel/subsystems/linux/syscall.cpp
//                 --out kernel/subsystems/linux/linux_syscall_table_generated.h
//
// Source data: tools/linux-compat/linux-syscalls-x86_64.csv
// Total syscalls listed: 374
// Implemented (Do<Name> body in some syscall_*.cpp): 267
// Dispatched (kSys<Name> case but no Do<Name>; inline impl): 93
// Effective coverage (Implemented + Dispatched): 360
// Coverage (implemented): 71%
// Coverage (effective): 96%
//
// See tools/linux-compat/README.md for provenance.

#pragma once

#include "util/types.h"

namespace duetos::subsystems::linux
{

enum class HandlerState : u8
{
    Unknown = 0,   // number outside the known ABI range
    Unimplemented, // deliberate -ENOSYS (kSysEnosys_-block) or no kSys constant at all
    Dispatched,    // kSys<Name> case exists in dispatch but no Do<Name> body
                   // (inline impl, alias to non-Do<Name> fn, etc.). Returns a
                   // coherent value to userspace, just not via the Do<Name>
                   // convention the script's heuristic looks for.
    Implemented,   // known name, matching Do<Name> handler exists in some
                   // syscall_*.cpp peer.
};

struct LinuxSyscallEntry
{
    u16 number;
    u8 args; // 0..6
    HandlerState state;
    const char* name;
};

/// Dense-by-number, sorted table of every known x86_64 Linux syscall.
inline constexpr LinuxSyscallEntry kLinuxSyscalls[] = {
    {0, 3, HandlerState::Implemented, "read"},
    {1, 3, HandlerState::Implemented, "write"},
    {2, 3, HandlerState::Implemented, "open"},
    {3, 1, HandlerState::Implemented, "close"},
    {4, 2, HandlerState::Implemented, "stat"},
    {5, 2, HandlerState::Implemented, "fstat"},
    {6, 2, HandlerState::Implemented, "lstat"},
    {7, 3, HandlerState::Implemented, "poll"},
    {8, 3, HandlerState::Implemented, "lseek"},
    {9, 6, HandlerState::Implemented, "mmap"},
    {10, 3, HandlerState::Implemented, "mprotect"},
    {11, 2, HandlerState::Implemented, "munmap"},
    {12, 1, HandlerState::Implemented, "brk"},
    {13, 4, HandlerState::Implemented, "rt_sigaction"},
    {14, 4, HandlerState::Implemented, "rt_sigprocmask"},
    {15, 0, HandlerState::Implemented, "rt_sigreturn"},
    {16, 3, HandlerState::Implemented, "ioctl"},
    {17, 4, HandlerState::Implemented, "pread64"},
    {18, 4, HandlerState::Implemented, "pwrite64"},
    {19, 3, HandlerState::Implemented, "readv"},
    {20, 3, HandlerState::Implemented, "writev"},
    {21, 2, HandlerState::Implemented, "access"},
    {22, 1, HandlerState::Implemented, "pipe"},
    {23, 5, HandlerState::Implemented, "select"},
    {24, 0, HandlerState::Implemented, "sched_yield"},
    {25, 5, HandlerState::Implemented, "mremap"},
    {26, 3, HandlerState::Implemented, "msync"},
    {27, 3, HandlerState::Implemented, "mincore"},
    {28, 3, HandlerState::Implemented, "madvise"},
    {29, 3, HandlerState::Dispatched, "shmget"},
    {30, 3, HandlerState::Dispatched, "shmat"},
    {31, 3, HandlerState::Dispatched, "shmctl"},
    {32, 1, HandlerState::Implemented, "dup"},
    {33, 2, HandlerState::Implemented, "dup2"},
    {34, 0, HandlerState::Implemented, "pause"},
    {35, 2, HandlerState::Implemented, "nanosleep"},
    {36, 2, HandlerState::Implemented, "getitimer"},
    {37, 1, HandlerState::Implemented, "alarm"},
    {38, 3, HandlerState::Implemented, "setitimer"},
    {39, 0, HandlerState::Implemented, "getpid"},
    {40, 4, HandlerState::Implemented, "sendfile"},
    {41, 3, HandlerState::Implemented, "socket"},
    {42, 3, HandlerState::Implemented, "connect"},
    {43, 3, HandlerState::Implemented, "accept"},
    {44, 6, HandlerState::Implemented, "sendto"},
    {45, 6, HandlerState::Implemented, "recvfrom"},
    {46, 3, HandlerState::Implemented, "sendmsg"},
    {47, 3, HandlerState::Implemented, "recvmsg"},
    {48, 2, HandlerState::Implemented, "shutdown"},
    {49, 3, HandlerState::Implemented, "bind"},
    {50, 2, HandlerState::Implemented, "listen"},
    {51, 3, HandlerState::Implemented, "getsockname"},
    {52, 3, HandlerState::Implemented, "getpeername"},
    {53, 4, HandlerState::Implemented, "socketpair"},
    {54, 5, HandlerState::Implemented, "setsockopt"},
    {55, 5, HandlerState::Implemented, "getsockopt"},
    {56, 5, HandlerState::Implemented, "clone"},
    {57, 0, HandlerState::Implemented, "fork"},
    {58, 0, HandlerState::Dispatched, "vfork"},
    {59, 3, HandlerState::Dispatched, "execve"},
    {60, 1, HandlerState::Implemented, "exit"},
    {61, 4, HandlerState::Implemented, "wait4"},
    {62, 2, HandlerState::Implemented, "kill"},
    {63, 1, HandlerState::Implemented, "uname"},
    {64, 3, HandlerState::Dispatched, "semget"},
    {65, 3, HandlerState::Dispatched, "semop"},
    {66, 4, HandlerState::Dispatched, "semctl"},
    {67, 1, HandlerState::Dispatched, "shmdt"},
    {68, 2, HandlerState::Dispatched, "msgget"},
    {69, 4, HandlerState::Dispatched, "msgsnd"},
    {70, 5, HandlerState::Dispatched, "msgrcv"},
    {71, 3, HandlerState::Dispatched, "msgctl"},
    {72, 3, HandlerState::Implemented, "fcntl"},
    {73, 2, HandlerState::Implemented, "flock"},
    {74, 1, HandlerState::Implemented, "fsync"},
    {75, 1, HandlerState::Implemented, "fdatasync"},
    {76, 2, HandlerState::Implemented, "truncate"},
    {77, 2, HandlerState::Implemented, "ftruncate"},
    {78, 3, HandlerState::Implemented, "getdents"},
    {79, 2, HandlerState::Implemented, "getcwd"},
    {80, 1, HandlerState::Implemented, "chdir"},
    {81, 1, HandlerState::Implemented, "fchdir"},
    {82, 2, HandlerState::Implemented, "rename"},
    {83, 2, HandlerState::Implemented, "mkdir"},
    {84, 1, HandlerState::Implemented, "rmdir"},
    {85, 2, HandlerState::Implemented, "creat"},
    {86, 2, HandlerState::Implemented, "link"},
    {87, 1, HandlerState::Implemented, "unlink"},
    {88, 2, HandlerState::Implemented, "symlink"},
    {89, 3, HandlerState::Implemented, "readlink"},
    {90, 2, HandlerState::Implemented, "chmod"},
    {91, 2, HandlerState::Implemented, "fchmod"},
    {92, 3, HandlerState::Implemented, "chown"},
    {93, 3, HandlerState::Implemented, "fchown"},
    {94, 3, HandlerState::Implemented, "lchown"},
    {95, 1, HandlerState::Dispatched, "umask"},
    {96, 2, HandlerState::Implemented, "gettimeofday"},
    {97, 2, HandlerState::Implemented, "getrlimit"},
    {98, 2, HandlerState::Implemented, "getrusage"},
    {99, 1, HandlerState::Implemented, "sysinfo"},
    {100, 1, HandlerState::Implemented, "times"},
    {101, 4, HandlerState::Implemented, "ptrace"},
    {102, 0, HandlerState::Implemented, "getuid"},
    {103, 3, HandlerState::Implemented, "syslog"},
    {104, 0, HandlerState::Implemented, "getgid"},
    {105, 1, HandlerState::Implemented, "setuid"},
    {106, 1, HandlerState::Implemented, "setgid"},
    {107, 0, HandlerState::Implemented, "geteuid"},
    {108, 0, HandlerState::Implemented, "getegid"},
    {109, 2, HandlerState::Implemented, "setpgid"},
    {110, 0, HandlerState::Implemented, "getppid"},
    {111, 0, HandlerState::Implemented, "getpgrp"},
    {112, 0, HandlerState::Implemented, "setsid"},
    {113, 2, HandlerState::Implemented, "setreuid"},
    {114, 2, HandlerState::Implemented, "setregid"},
    {115, 2, HandlerState::Implemented, "getgroups"},
    {116, 2, HandlerState::Implemented, "setgroups"},
    {117, 3, HandlerState::Implemented, "setresuid"},
    {118, 3, HandlerState::Implemented, "getresuid"},
    {119, 3, HandlerState::Implemented, "setresgid"},
    {120, 3, HandlerState::Implemented, "getresgid"},
    {121, 1, HandlerState::Implemented, "getpgid"},
    {122, 1, HandlerState::Implemented, "setfsuid"},
    {123, 1, HandlerState::Implemented, "setfsgid"},
    {124, 1, HandlerState::Implemented, "getsid"},
    {125, 2, HandlerState::Implemented, "capget"},
    {126, 2, HandlerState::Implemented, "capset"},
    {127, 2, HandlerState::Implemented, "rt_sigpending"},
    {128, 4, HandlerState::Implemented, "rt_sigtimedwait"},
    {129, 3, HandlerState::Implemented, "rt_sigqueueinfo"},
    {130, 2, HandlerState::Implemented, "rt_sigsuspend"},
    {131, 2, HandlerState::Implemented, "sigaltstack"},
    {132, 2, HandlerState::Implemented, "utime"},
    {133, 3, HandlerState::Implemented, "mknod"},
    {134, 1, HandlerState::Implemented, "uselib"},
    {135, 1, HandlerState::Implemented, "personality"},
    {136, 2, HandlerState::Unimplemented, "ustat"},
    {137, 2, HandlerState::Dispatched, "statfs"},
    {138, 2, HandlerState::Dispatched, "fstatfs"},
    {139, 3, HandlerState::Unimplemented, "sysfs"},
    {140, 2, HandlerState::Implemented, "getpriority"},
    {141, 3, HandlerState::Implemented, "setpriority"},
    {142, 2, HandlerState::Implemented, "sched_setparam"},
    {143, 2, HandlerState::Implemented, "sched_getparam"},
    {144, 3, HandlerState::Implemented, "sched_setscheduler"},
    {145, 1, HandlerState::Implemented, "sched_getscheduler"},
    {146, 1, HandlerState::Implemented, "sched_get_priority_max"},
    {147, 1, HandlerState::Implemented, "sched_get_priority_min"},
    {148, 2, HandlerState::Implemented, "sched_rr_get_interval"},
    {149, 2, HandlerState::Implemented, "mlock"},
    {150, 2, HandlerState::Implemented, "munlock"},
    {151, 1, HandlerState::Implemented, "mlockall"},
    {152, 0, HandlerState::Implemented, "munlockall"},
    {153, 0, HandlerState::Implemented, "vhangup"},
    {154, 3, HandlerState::Implemented, "modify_ldt"},
    {155, 2, HandlerState::Dispatched, "pivot_root"},
    {156, 1, HandlerState::Unimplemented, "_sysctl"},
    {157, 5, HandlerState::Implemented, "prctl"},
    {158, 2, HandlerState::Implemented, "arch_prctl"},
    {159, 1, HandlerState::Implemented, "adjtimex"},
    {160, 2, HandlerState::Implemented, "setrlimit"},
    {161, 1, HandlerState::Dispatched, "chroot"},
    {162, 0, HandlerState::Implemented, "sync"},
    {163, 1, HandlerState::Implemented, "acct"},
    {164, 2, HandlerState::Implemented, "settimeofday"},
    {165, 5, HandlerState::Implemented, "mount"},
    {166, 2, HandlerState::Implemented, "umount2"},
    {167, 2, HandlerState::Dispatched, "swapon"},
    {168, 1, HandlerState::Dispatched, "swapoff"},
    {169, 4, HandlerState::Dispatched, "reboot"},
    {170, 2, HandlerState::Dispatched, "sethostname"},
    {171, 2, HandlerState::Dispatched, "setdomainname"},
    {172, 1, HandlerState::Dispatched, "iopl"},
    {173, 3, HandlerState::Dispatched, "ioperm"},
    {174, 0, HandlerState::Unimplemented, "create_module"},
    {175, 3, HandlerState::Dispatched, "init_module"},
    {176, 2, HandlerState::Dispatched, "delete_module"},
    {177, 0, HandlerState::Unimplemented, "get_kernel_syms"},
    {178, 0, HandlerState::Unimplemented, "query_module"},
    {179, 4, HandlerState::Dispatched, "quotactl"},
    {180, 0, HandlerState::Unimplemented, "nfsservctl"},
    {181, 0, HandlerState::Unimplemented, "getpmsg"},
    {182, 0, HandlerState::Unimplemented, "putpmsg"},
    {183, 0, HandlerState::Unimplemented, "afs_syscall"},
    {184, 0, HandlerState::Unimplemented, "tuxcall"},
    {185, 0, HandlerState::Unimplemented, "security"},
    {186, 0, HandlerState::Implemented, "gettid"},
    {187, 3, HandlerState::Implemented, "readahead"},
    {188, 5, HandlerState::Implemented, "setxattr"},
    {189, 5, HandlerState::Implemented, "lsetxattr"},
    {190, 5, HandlerState::Implemented, "fsetxattr"},
    {191, 4, HandlerState::Implemented, "getxattr"},
    {192, 4, HandlerState::Implemented, "lgetxattr"},
    {193, 4, HandlerState::Implemented, "fgetxattr"},
    {194, 3, HandlerState::Implemented, "listxattr"},
    {195, 3, HandlerState::Implemented, "llistxattr"},
    {196, 3, HandlerState::Implemented, "flistxattr"},
    {197, 2, HandlerState::Implemented, "removexattr"},
    {198, 2, HandlerState::Implemented, "lremovexattr"},
    {199, 2, HandlerState::Implemented, "fremovexattr"},
    {200, 2, HandlerState::Implemented, "tkill"},
    {201, 1, HandlerState::Implemented, "time"},
    {202, 6, HandlerState::Implemented, "futex"},
    {203, 3, HandlerState::Implemented, "sched_setaffinity"},
    {204, 3, HandlerState::Implemented, "sched_getaffinity"},
    {205, 1, HandlerState::Implemented, "set_thread_area"},
    {206, 2, HandlerState::Dispatched, "io_setup"},
    {207, 1, HandlerState::Dispatched, "io_destroy"},
    {208, 4, HandlerState::Dispatched, "io_getevents"},
    {209, 3, HandlerState::Dispatched, "io_submit"},
    {210, 3, HandlerState::Dispatched, "io_cancel"},
    {211, 1, HandlerState::Implemented, "get_thread_area"},
    {212, 3, HandlerState::Unimplemented, "lookup_dcookie"},
    {213, 1, HandlerState::Implemented, "epoll_create"},
    {214, 0, HandlerState::Implemented, "epoll_ctl_old"},
    {215, 0, HandlerState::Implemented, "epoll_wait_old"},
    {216, 5, HandlerState::Implemented, "remap_file_pages"},
    {217, 3, HandlerState::Implemented, "getdents64"},
    {218, 1, HandlerState::Implemented, "set_tid_address"},
    {219, 0, HandlerState::Implemented, "restart_syscall"},
    {220, 4, HandlerState::Dispatched, "semtimedop"},
    {221, 4, HandlerState::Implemented, "fadvise64"},
    {222, 3, HandlerState::Implemented, "timer_create"},
    {223, 4, HandlerState::Implemented, "timer_settime"},
    {224, 2, HandlerState::Implemented, "timer_gettime"},
    {225, 1, HandlerState::Implemented, "timer_getoverrun"},
    {226, 1, HandlerState::Implemented, "timer_delete"},
    {227, 2, HandlerState::Implemented, "clock_settime"},
    {228, 2, HandlerState::Implemented, "clock_gettime"},
    {229, 2, HandlerState::Implemented, "clock_getres"},
    {230, 4, HandlerState::Implemented, "clock_nanosleep"},
    {231, 1, HandlerState::Implemented, "exit_group"},
    {232, 4, HandlerState::Implemented, "epoll_wait"},
    {233, 4, HandlerState::Implemented, "epoll_ctl"},
    {234, 3, HandlerState::Implemented, "tgkill"},
    {235, 2, HandlerState::Implemented, "utimes"},
    {236, 0, HandlerState::Unimplemented, "vserver"},
    {237, 6, HandlerState::Dispatched, "mbind"},
    {238, 3, HandlerState::Dispatched, "set_mempolicy"},
    {239, 5, HandlerState::Dispatched, "get_mempolicy"},
    {240, 4, HandlerState::Dispatched, "mq_open"},
    {241, 1, HandlerState::Dispatched, "mq_unlink"},
    {242, 5, HandlerState::Dispatched, "mq_timedsend"},
    {243, 5, HandlerState::Dispatched, "mq_timedreceive"},
    {244, 2, HandlerState::Dispatched, "mq_notify"},
    {245, 3, HandlerState::Dispatched, "mq_getsetattr"},
    {246, 4, HandlerState::Dispatched, "kexec_load"},
    {247, 5, HandlerState::Implemented, "waitid"},
    {248, 5, HandlerState::Dispatched, "add_key"},
    {249, 4, HandlerState::Dispatched, "request_key"},
    {250, 5, HandlerState::Dispatched, "keyctl"},
    {251, 3, HandlerState::Implemented, "ioprio_set"},
    {252, 2, HandlerState::Implemented, "ioprio_get"},
    {253, 0, HandlerState::Dispatched, "inotify_init"},
    {254, 3, HandlerState::Dispatched, "inotify_add_watch"},
    {255, 2, HandlerState::Dispatched, "inotify_rm_watch"},
    {256, 4, HandlerState::Dispatched, "migrate_pages"},
    {257, 4, HandlerState::Implemented, "openat"},
    {258, 3, HandlerState::Implemented, "mkdirat"},
    {259, 4, HandlerState::Implemented, "mknodat"},
    {260, 5, HandlerState::Implemented, "fchownat"},
    {261, 3, HandlerState::Implemented, "futimesat"},
    {262, 4, HandlerState::Implemented, "newfstatat"},
    {263, 3, HandlerState::Implemented, "unlinkat"},
    {264, 4, HandlerState::Implemented, "renameat"},
    {265, 5, HandlerState::Implemented, "linkat"},
    {266, 3, HandlerState::Implemented, "symlinkat"},
    {267, 4, HandlerState::Implemented, "readlinkat"},
    {268, 3, HandlerState::Implemented, "fchmodat"},
    {269, 3, HandlerState::Implemented, "faccessat"},
    {270, 6, HandlerState::Implemented, "pselect6"},
    {271, 5, HandlerState::Implemented, "ppoll"},
    {272, 1, HandlerState::Implemented, "unshare"},
    {273, 2, HandlerState::Implemented, "set_robust_list"},
    {274, 3, HandlerState::Implemented, "get_robust_list"},
    {275, 6, HandlerState::Dispatched, "splice"},
    {276, 4, HandlerState::Dispatched, "tee"},
    {277, 4, HandlerState::Implemented, "sync_file_range"},
    {278, 4, HandlerState::Dispatched, "vmsplice"},
    {279, 6, HandlerState::Dispatched, "move_pages"},
    {280, 4, HandlerState::Implemented, "utimensat"},
    {281, 6, HandlerState::Implemented, "epoll_pwait"},
    {282, 3, HandlerState::Implemented, "signalfd"},
    {283, 2, HandlerState::Implemented, "timerfd_create"},
    {284, 1, HandlerState::Implemented, "eventfd"},
    {285, 4, HandlerState::Implemented, "fallocate"},
    {286, 4, HandlerState::Implemented, "timerfd_settime"},
    {287, 2, HandlerState::Implemented, "timerfd_gettime"},
    {288, 4, HandlerState::Implemented, "accept4"},
    {289, 4, HandlerState::Dispatched, "signalfd4"},
    {290, 2, HandlerState::Implemented, "eventfd2"},
    {291, 1, HandlerState::Implemented, "epoll_create1"},
    {292, 3, HandlerState::Implemented, "dup3"},
    {293, 2, HandlerState::Implemented, "pipe2"},
    {294, 1, HandlerState::Dispatched, "inotify_init1"},
    {295, 5, HandlerState::Implemented, "preadv"},
    {296, 5, HandlerState::Implemented, "pwritev"},
    {297, 4, HandlerState::Implemented, "rt_tgsigqueueinfo"},
    {298, 5, HandlerState::Dispatched, "perf_event_open"},
    {299, 5, HandlerState::Implemented, "recvmmsg"},
    {300, 2, HandlerState::Dispatched, "fanotify_init"},
    {301, 5, HandlerState::Dispatched, "fanotify_mark"},
    {302, 4, HandlerState::Implemented, "prlimit64"},
    {303, 5, HandlerState::Dispatched, "name_to_handle_at"},
    {304, 3, HandlerState::Dispatched, "open_by_handle_at"},
    {305, 2, HandlerState::Implemented, "clock_adjtime"},
    {306, 1, HandlerState::Implemented, "syncfs"},
    {307, 4, HandlerState::Implemented, "sendmmsg"},
    {308, 2, HandlerState::Implemented, "setns"},
    {309, 3, HandlerState::Implemented, "getcpu"},
    {310, 6, HandlerState::Implemented, "process_vm_readv"},
    {311, 6, HandlerState::Implemented, "process_vm_writev"},
    {312, 5, HandlerState::Implemented, "kcmp"},
    {313, 3, HandlerState::Dispatched, "finit_module"},
    {314, 3, HandlerState::Implemented, "sched_setattr"},
    {315, 4, HandlerState::Implemented, "sched_getattr"},
    {316, 5, HandlerState::Implemented, "renameat2"},
    {317, 3, HandlerState::Implemented, "seccomp"},
    {318, 3, HandlerState::Implemented, "getrandom"},
    {319, 2, HandlerState::Dispatched, "memfd_create"},
    {320, 5, HandlerState::Dispatched, "kexec_file_load"},
    {321, 3, HandlerState::Dispatched, "bpf"},
    {322, 5, HandlerState::Dispatched, "execveat"},
    {323, 1, HandlerState::Dispatched, "userfaultfd"},
    {324, 2, HandlerState::Implemented, "membarrier"},
    {325, 3, HandlerState::Implemented, "mlock2"},
    {326, 6, HandlerState::Dispatched, "copy_file_range"},
    {327, 6, HandlerState::Implemented, "preadv2"},
    {328, 6, HandlerState::Implemented, "pwritev2"},
    {329, 4, HandlerState::Dispatched, "pkey_mprotect"},
    {330, 2, HandlerState::Dispatched, "pkey_alloc"},
    {331, 1, HandlerState::Dispatched, "pkey_free"},
    {332, 5, HandlerState::Dispatched, "statx"},
    {333, 6, HandlerState::Implemented, "io_pgetevents"},
    {334, 4, HandlerState::Implemented, "rseq"},
    {424, 4, HandlerState::Dispatched, "pidfd_send_signal"},
    {425, 2, HandlerState::Dispatched, "io_uring_setup"},
    {426, 6, HandlerState::Dispatched, "io_uring_enter"},
    {427, 4, HandlerState::Dispatched, "io_uring_register"},
    {428, 3, HandlerState::Dispatched, "open_tree"},
    {429, 5, HandlerState::Dispatched, "move_mount"},
    {430, 2, HandlerState::Dispatched, "fsopen"},
    {431, 5, HandlerState::Dispatched, "fsconfig"},
    {432, 3, HandlerState::Dispatched, "fsmount"},
    {433, 3, HandlerState::Dispatched, "fspick"},
    {434, 2, HandlerState::Dispatched, "pidfd_open"},
    {435, 2, HandlerState::Implemented, "clone3"},
    {436, 3, HandlerState::Dispatched, "close_range"},
    {437, 4, HandlerState::Implemented, "openat2"},
    {438, 3, HandlerState::Dispatched, "pidfd_getfd"},
    {439, 4, HandlerState::Implemented, "faccessat2"},
    {440, 5, HandlerState::Dispatched, "process_madvise"},
    {441, 6, HandlerState::Implemented, "epoll_pwait2"},
    {442, 5, HandlerState::Dispatched, "mount_setattr"},
    {443, 4, HandlerState::Implemented, "quotactl_fd"},
    {444, 3, HandlerState::Dispatched, "landlock_create_ruleset"},
    {445, 4, HandlerState::Dispatched, "landlock_add_rule"},
    {446, 2, HandlerState::Dispatched, "landlock_restrict_self"},
    {447, 1, HandlerState::Implemented, "memfd_secret"},
    {448, 2, HandlerState::Dispatched, "process_mrelease"},
    {449, 5, HandlerState::Implemented, "futex_waitv"},
    {450, 4, HandlerState::Implemented, "set_mempolicy_home_node"},
    {451, 4, HandlerState::Implemented, "cachestat"},
    {452, 4, HandlerState::Implemented, "fchmodat2"},
    {453, 3, HandlerState::Implemented, "map_shadow_stack"},
    {454, 4, HandlerState::Implemented, "futex_wake"},
    {455, 6, HandlerState::Implemented, "futex_wait"},
    {456, 4, HandlerState::Implemented, "futex_requeue"},
    {457, 4, HandlerState::Implemented, "statmount"},
    {458, 4, HandlerState::Implemented, "listmount"},
    {459, 4, HandlerState::Implemented, "lsm_get_self_attr"},
    {460, 4, HandlerState::Implemented, "lsm_set_self_attr"},
    {461, 3, HandlerState::Implemented, "lsm_list_modules"},
    {462, 3, HandlerState::Dispatched, "mseal"},
};

inline constexpr u32 kLinuxSyscallCount = sizeof(kLinuxSyscalls) / sizeof(kLinuxSyscalls[0]);

inline constexpr u32 kLinuxSyscallMaxNumber = 462;

/// Dense index by syscall number. Unknown numbers map to nullptr.
/// This keeps lookup O(1) while preserving the historical API.
inline constexpr const LinuxSyscallEntry* kLinuxSyscallByNumber[] = {
    &kLinuxSyscalls[0],
    &kLinuxSyscalls[1],
    &kLinuxSyscalls[2],
    &kLinuxSyscalls[3],
    &kLinuxSyscalls[4],
    &kLinuxSyscalls[5],
    &kLinuxSyscalls[6],
    &kLinuxSyscalls[7],
    &kLinuxSyscalls[8],
    &kLinuxSyscalls[9],
    &kLinuxSyscalls[10],
    &kLinuxSyscalls[11],
    &kLinuxSyscalls[12],
    &kLinuxSyscalls[13],
    &kLinuxSyscalls[14],
    &kLinuxSyscalls[15],
    &kLinuxSyscalls[16],
    &kLinuxSyscalls[17],
    &kLinuxSyscalls[18],
    &kLinuxSyscalls[19],
    &kLinuxSyscalls[20],
    &kLinuxSyscalls[21],
    &kLinuxSyscalls[22],
    &kLinuxSyscalls[23],
    &kLinuxSyscalls[24],
    &kLinuxSyscalls[25],
    &kLinuxSyscalls[26],
    &kLinuxSyscalls[27],
    &kLinuxSyscalls[28],
    &kLinuxSyscalls[29],
    &kLinuxSyscalls[30],
    &kLinuxSyscalls[31],
    &kLinuxSyscalls[32],
    &kLinuxSyscalls[33],
    &kLinuxSyscalls[34],
    &kLinuxSyscalls[35],
    &kLinuxSyscalls[36],
    &kLinuxSyscalls[37],
    &kLinuxSyscalls[38],
    &kLinuxSyscalls[39],
    &kLinuxSyscalls[40],
    &kLinuxSyscalls[41],
    &kLinuxSyscalls[42],
    &kLinuxSyscalls[43],
    &kLinuxSyscalls[44],
    &kLinuxSyscalls[45],
    &kLinuxSyscalls[46],
    &kLinuxSyscalls[47],
    &kLinuxSyscalls[48],
    &kLinuxSyscalls[49],
    &kLinuxSyscalls[50],
    &kLinuxSyscalls[51],
    &kLinuxSyscalls[52],
    &kLinuxSyscalls[53],
    &kLinuxSyscalls[54],
    &kLinuxSyscalls[55],
    &kLinuxSyscalls[56],
    &kLinuxSyscalls[57],
    &kLinuxSyscalls[58],
    &kLinuxSyscalls[59],
    &kLinuxSyscalls[60],
    &kLinuxSyscalls[61],
    &kLinuxSyscalls[62],
    &kLinuxSyscalls[63],
    &kLinuxSyscalls[64],
    &kLinuxSyscalls[65],
    &kLinuxSyscalls[66],
    &kLinuxSyscalls[67],
    &kLinuxSyscalls[68],
    &kLinuxSyscalls[69],
    &kLinuxSyscalls[70],
    &kLinuxSyscalls[71],
    &kLinuxSyscalls[72],
    &kLinuxSyscalls[73],
    &kLinuxSyscalls[74],
    &kLinuxSyscalls[75],
    &kLinuxSyscalls[76],
    &kLinuxSyscalls[77],
    &kLinuxSyscalls[78],
    &kLinuxSyscalls[79],
    &kLinuxSyscalls[80],
    &kLinuxSyscalls[81],
    &kLinuxSyscalls[82],
    &kLinuxSyscalls[83],
    &kLinuxSyscalls[84],
    &kLinuxSyscalls[85],
    &kLinuxSyscalls[86],
    &kLinuxSyscalls[87],
    &kLinuxSyscalls[88],
    &kLinuxSyscalls[89],
    &kLinuxSyscalls[90],
    &kLinuxSyscalls[91],
    &kLinuxSyscalls[92],
    &kLinuxSyscalls[93],
    &kLinuxSyscalls[94],
    &kLinuxSyscalls[95],
    &kLinuxSyscalls[96],
    &kLinuxSyscalls[97],
    &kLinuxSyscalls[98],
    &kLinuxSyscalls[99],
    &kLinuxSyscalls[100],
    &kLinuxSyscalls[101],
    &kLinuxSyscalls[102],
    &kLinuxSyscalls[103],
    &kLinuxSyscalls[104],
    &kLinuxSyscalls[105],
    &kLinuxSyscalls[106],
    &kLinuxSyscalls[107],
    &kLinuxSyscalls[108],
    &kLinuxSyscalls[109],
    &kLinuxSyscalls[110],
    &kLinuxSyscalls[111],
    &kLinuxSyscalls[112],
    &kLinuxSyscalls[113],
    &kLinuxSyscalls[114],
    &kLinuxSyscalls[115],
    &kLinuxSyscalls[116],
    &kLinuxSyscalls[117],
    &kLinuxSyscalls[118],
    &kLinuxSyscalls[119],
    &kLinuxSyscalls[120],
    &kLinuxSyscalls[121],
    &kLinuxSyscalls[122],
    &kLinuxSyscalls[123],
    &kLinuxSyscalls[124],
    &kLinuxSyscalls[125],
    &kLinuxSyscalls[126],
    &kLinuxSyscalls[127],
    &kLinuxSyscalls[128],
    &kLinuxSyscalls[129],
    &kLinuxSyscalls[130],
    &kLinuxSyscalls[131],
    &kLinuxSyscalls[132],
    &kLinuxSyscalls[133],
    &kLinuxSyscalls[134],
    &kLinuxSyscalls[135],
    &kLinuxSyscalls[136],
    &kLinuxSyscalls[137],
    &kLinuxSyscalls[138],
    &kLinuxSyscalls[139],
    &kLinuxSyscalls[140],
    &kLinuxSyscalls[141],
    &kLinuxSyscalls[142],
    &kLinuxSyscalls[143],
    &kLinuxSyscalls[144],
    &kLinuxSyscalls[145],
    &kLinuxSyscalls[146],
    &kLinuxSyscalls[147],
    &kLinuxSyscalls[148],
    &kLinuxSyscalls[149],
    &kLinuxSyscalls[150],
    &kLinuxSyscalls[151],
    &kLinuxSyscalls[152],
    &kLinuxSyscalls[153],
    &kLinuxSyscalls[154],
    &kLinuxSyscalls[155],
    &kLinuxSyscalls[156],
    &kLinuxSyscalls[157],
    &kLinuxSyscalls[158],
    &kLinuxSyscalls[159],
    &kLinuxSyscalls[160],
    &kLinuxSyscalls[161],
    &kLinuxSyscalls[162],
    &kLinuxSyscalls[163],
    &kLinuxSyscalls[164],
    &kLinuxSyscalls[165],
    &kLinuxSyscalls[166],
    &kLinuxSyscalls[167],
    &kLinuxSyscalls[168],
    &kLinuxSyscalls[169],
    &kLinuxSyscalls[170],
    &kLinuxSyscalls[171],
    &kLinuxSyscalls[172],
    &kLinuxSyscalls[173],
    &kLinuxSyscalls[174],
    &kLinuxSyscalls[175],
    &kLinuxSyscalls[176],
    &kLinuxSyscalls[177],
    &kLinuxSyscalls[178],
    &kLinuxSyscalls[179],
    &kLinuxSyscalls[180],
    &kLinuxSyscalls[181],
    &kLinuxSyscalls[182],
    &kLinuxSyscalls[183],
    &kLinuxSyscalls[184],
    &kLinuxSyscalls[185],
    &kLinuxSyscalls[186],
    &kLinuxSyscalls[187],
    &kLinuxSyscalls[188],
    &kLinuxSyscalls[189],
    &kLinuxSyscalls[190],
    &kLinuxSyscalls[191],
    &kLinuxSyscalls[192],
    &kLinuxSyscalls[193],
    &kLinuxSyscalls[194],
    &kLinuxSyscalls[195],
    &kLinuxSyscalls[196],
    &kLinuxSyscalls[197],
    &kLinuxSyscalls[198],
    &kLinuxSyscalls[199],
    &kLinuxSyscalls[200],
    &kLinuxSyscalls[201],
    &kLinuxSyscalls[202],
    &kLinuxSyscalls[203],
    &kLinuxSyscalls[204],
    &kLinuxSyscalls[205],
    &kLinuxSyscalls[206],
    &kLinuxSyscalls[207],
    &kLinuxSyscalls[208],
    &kLinuxSyscalls[209],
    &kLinuxSyscalls[210],
    &kLinuxSyscalls[211],
    &kLinuxSyscalls[212],
    &kLinuxSyscalls[213],
    &kLinuxSyscalls[214],
    &kLinuxSyscalls[215],
    &kLinuxSyscalls[216],
    &kLinuxSyscalls[217],
    &kLinuxSyscalls[218],
    &kLinuxSyscalls[219],
    &kLinuxSyscalls[220],
    &kLinuxSyscalls[221],
    &kLinuxSyscalls[222],
    &kLinuxSyscalls[223],
    &kLinuxSyscalls[224],
    &kLinuxSyscalls[225],
    &kLinuxSyscalls[226],
    &kLinuxSyscalls[227],
    &kLinuxSyscalls[228],
    &kLinuxSyscalls[229],
    &kLinuxSyscalls[230],
    &kLinuxSyscalls[231],
    &kLinuxSyscalls[232],
    &kLinuxSyscalls[233],
    &kLinuxSyscalls[234],
    &kLinuxSyscalls[235],
    &kLinuxSyscalls[236],
    &kLinuxSyscalls[237],
    &kLinuxSyscalls[238],
    &kLinuxSyscalls[239],
    &kLinuxSyscalls[240],
    &kLinuxSyscalls[241],
    &kLinuxSyscalls[242],
    &kLinuxSyscalls[243],
    &kLinuxSyscalls[244],
    &kLinuxSyscalls[245],
    &kLinuxSyscalls[246],
    &kLinuxSyscalls[247],
    &kLinuxSyscalls[248],
    &kLinuxSyscalls[249],
    &kLinuxSyscalls[250],
    &kLinuxSyscalls[251],
    &kLinuxSyscalls[252],
    &kLinuxSyscalls[253],
    &kLinuxSyscalls[254],
    &kLinuxSyscalls[255],
    &kLinuxSyscalls[256],
    &kLinuxSyscalls[257],
    &kLinuxSyscalls[258],
    &kLinuxSyscalls[259],
    &kLinuxSyscalls[260],
    &kLinuxSyscalls[261],
    &kLinuxSyscalls[262],
    &kLinuxSyscalls[263],
    &kLinuxSyscalls[264],
    &kLinuxSyscalls[265],
    &kLinuxSyscalls[266],
    &kLinuxSyscalls[267],
    &kLinuxSyscalls[268],
    &kLinuxSyscalls[269],
    &kLinuxSyscalls[270],
    &kLinuxSyscalls[271],
    &kLinuxSyscalls[272],
    &kLinuxSyscalls[273],
    &kLinuxSyscalls[274],
    &kLinuxSyscalls[275],
    &kLinuxSyscalls[276],
    &kLinuxSyscalls[277],
    &kLinuxSyscalls[278],
    &kLinuxSyscalls[279],
    &kLinuxSyscalls[280],
    &kLinuxSyscalls[281],
    &kLinuxSyscalls[282],
    &kLinuxSyscalls[283],
    &kLinuxSyscalls[284],
    &kLinuxSyscalls[285],
    &kLinuxSyscalls[286],
    &kLinuxSyscalls[287],
    &kLinuxSyscalls[288],
    &kLinuxSyscalls[289],
    &kLinuxSyscalls[290],
    &kLinuxSyscalls[291],
    &kLinuxSyscalls[292],
    &kLinuxSyscalls[293],
    &kLinuxSyscalls[294],
    &kLinuxSyscalls[295],
    &kLinuxSyscalls[296],
    &kLinuxSyscalls[297],
    &kLinuxSyscalls[298],
    &kLinuxSyscalls[299],
    &kLinuxSyscalls[300],
    &kLinuxSyscalls[301],
    &kLinuxSyscalls[302],
    &kLinuxSyscalls[303],
    &kLinuxSyscalls[304],
    &kLinuxSyscalls[305],
    &kLinuxSyscalls[306],
    &kLinuxSyscalls[307],
    &kLinuxSyscalls[308],
    &kLinuxSyscalls[309],
    &kLinuxSyscalls[310],
    &kLinuxSyscalls[311],
    &kLinuxSyscalls[312],
    &kLinuxSyscalls[313],
    &kLinuxSyscalls[314],
    &kLinuxSyscalls[315],
    &kLinuxSyscalls[316],
    &kLinuxSyscalls[317],
    &kLinuxSyscalls[318],
    &kLinuxSyscalls[319],
    &kLinuxSyscalls[320],
    &kLinuxSyscalls[321],
    &kLinuxSyscalls[322],
    &kLinuxSyscalls[323],
    &kLinuxSyscalls[324],
    &kLinuxSyscalls[325],
    &kLinuxSyscalls[326],
    &kLinuxSyscalls[327],
    &kLinuxSyscalls[328],
    &kLinuxSyscalls[329],
    &kLinuxSyscalls[330],
    &kLinuxSyscalls[331],
    &kLinuxSyscalls[332],
    &kLinuxSyscalls[333],
    &kLinuxSyscalls[334],
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    &kLinuxSyscalls[335],
    &kLinuxSyscalls[336],
    &kLinuxSyscalls[337],
    &kLinuxSyscalls[338],
    &kLinuxSyscalls[339],
    &kLinuxSyscalls[340],
    &kLinuxSyscalls[341],
    &kLinuxSyscalls[342],
    &kLinuxSyscalls[343],
    &kLinuxSyscalls[344],
    &kLinuxSyscalls[345],
    &kLinuxSyscalls[346],
    &kLinuxSyscalls[347],
    &kLinuxSyscalls[348],
    &kLinuxSyscalls[349],
    &kLinuxSyscalls[350],
    &kLinuxSyscalls[351],
    &kLinuxSyscalls[352],
    &kLinuxSyscalls[353],
    &kLinuxSyscalls[354],
    &kLinuxSyscalls[355],
    &kLinuxSyscalls[356],
    &kLinuxSyscalls[357],
    &kLinuxSyscalls[358],
    &kLinuxSyscalls[359],
    &kLinuxSyscalls[360],
    &kLinuxSyscalls[361],
    &kLinuxSyscalls[362],
    &kLinuxSyscalls[363],
    &kLinuxSyscalls[364],
    &kLinuxSyscalls[365],
    &kLinuxSyscalls[366],
    &kLinuxSyscalls[367],
    &kLinuxSyscalls[368],
    &kLinuxSyscalls[369],
    &kLinuxSyscalls[370],
    &kLinuxSyscalls[371],
    &kLinuxSyscalls[372],
    &kLinuxSyscalls[373],
};

inline constexpr u32 kLinuxSyscallHandlersImplemented = 267;
inline constexpr u32 kLinuxSyscallHandlersImplementedPrimary = 267;
inline constexpr u32 kLinuxSyscallHandlersImplementedEffective = 360;

/// Look up `nr` in the dense by-number index. Returns nullptr if unknown.
inline const LinuxSyscallEntry* LinuxSyscallLookup(u64 nr)
{
    if (nr > kLinuxSyscallMaxNumber)
        return nullptr;
    return kLinuxSyscallByNumber[static_cast<u32>(nr)];
}

} // namespace duetos::subsystems::linux
