#include "fs/ramfs.h"

#include "arch/x86_64/serial.h"
#include "loader/pe_loader.h"
#include "log/klog.h"
#include "sched/sched.h"
#include "subsystems/win32/thunks.h"
#include "syscall/syscall_names.h"

// Generated by tools/build/build-hello-pe.sh: a freestanding PE
// produced from userland/apps/hello_pe/hello.c. Exposes
// `kBinHelloPeBytes` and `kBinHelloPeBytes_len` in the
// duetos::fs::generated namespace. The build rule lives in
// kernel/CMakeLists.txt.
#include "generated_hello_pe.h"

// First PE that imports from kernel32.dll and is designed to
// be RESOLVED (not just reported) by the Win32 subsystem.
// Produced from userland/apps/hello_winapi/hello.c. Exercises
// the full chain: Import Directory -> IAT patch -> stub page
// -> int 0x80 SYS_EXIT.
#include "generated_customdll_test.h"
#include "generated_hello_winapi.h"
#include "generated_syscall_stress.h"
#include "generated_thread_stress.h"
#include "generated_windowed_hello.h"

// A real 3rd-party Windows PE embedded verbatim from
// userland/apps/windows_kill/windows-kill.exe. 79 KiB, 12 DLL
// imports, TLS callbacks — the v0 loader rejects it (no Win32
// subsystem) but PeReport still dumps the full gap on boot.
#include "generated_winkill_pe.h"

/*
 * Seed trees are declared at file scope as constinit data so the
 * whole structure lives in .rodata. Children arrays are similarly
 * constinit — each is an array of const RamfsNode* terminated by
 * nullptr, addressed by the parent's `children` field.
 *
 * Laying this out by hand (vs. generating from a manifest) is
 * appropriate for v0: three files, two directories per tree. The
 * moment a real disk backend exists, these seeds go away.
 */

namespace duetos::fs
{

namespace
{

constexpr u8 kEtcVersionBytes[] = "DuetOS v0 (ramfs-seeded)\n";
constexpr u8 kBinHelloBytes[] = "Hello from /bin/hello\n";
constexpr u8 kWelcomeBytes[] = "Welcome, sandbox. This file is all you can see.\n";

// A runnable ELF64 at /bin/exit.elf: 64-byte Ehdr + 56-byte Phdr
// + 9 bytes of code = 129 bytes total. Code: `mov eax, 0;
// xor edi, edi; int 0x80` — SYS_EXIT(0). Loadable by ElfLoad
// (proper validator passes: class=64, data=LSB, machine=x86_64,
// p_align=1 so the alignment invariant holds).
constexpr u8 kBinExitElfBytes[] = {
    // -- ELF64 header (64 bytes) --
    0x7F, 'E', 'L', 'F',                            // e_ident[0..3] magic
    0x02,                                           // EI_CLASS = ELFCLASS64
    0x01,                                           // EI_DATA = ELFDATA2LSB
    0x01,                                           // EI_VERSION = EV_CURRENT
    0x00,                                           // EI_OSABI = ELFOSABI_SYSV
    0x00,                                           // EI_ABIVERSION
    0, 0, 0, 0, 0, 0, 0,                            // padding (7 bytes)
    0x02, 0x00,                                     // e_type = ET_EXEC
    0x3E, 0x00,                                     // e_machine = EM_X86_64
    0x01, 0x00, 0x00, 0x00,                         // e_version
    0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, // e_entry = 0x400000
    0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // e_phoff = 64
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // e_shoff = 0
    0x00, 0x00, 0x00, 0x00,                         // e_flags
    0x40, 0x00,                                     // e_ehsize = 64
    0x38, 0x00,                                     // e_phentsize = 56
    0x01, 0x00,                                     // e_phnum = 1
    0x00, 0x00,                                     // e_shentsize
    0x00, 0x00,                                     // e_shnum
    0x00, 0x00,                                     // e_shstrndx

    // -- PT_LOAD program header (56 bytes) --
    0x01, 0x00, 0x00, 0x00,                         // p_type = PT_LOAD
    0x05, 0x00, 0x00, 0x00,                         // p_flags = PF_R | PF_X
    0x78, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // p_offset = 120
    0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, // p_vaddr = 0x400000
    0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, // p_paddr = 0x400000
    0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // p_filesz = 9
    0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // p_memsz = 9
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // p_align = 1

    // -- Code (9 bytes, at file offset 120, mapped at 0x400000) --
    0xB8, 0x00, 0x00, 0x00, 0x00, // mov eax, 0    (SYS_EXIT)
    0x31, 0xFF,                   // xor edi, edi  (exit code 0)
    0xCD, 0x80,                   // int 0x80
};

// /bin/usershell.elf — first userland ELF spawned at boot.
// Hand-built ELF64 (no compiler needed), 181 bytes total:
// 64-byte Ehdr + 56-byte Phdr + 40-byte code + 21-byte data.
// The code exercises three syscalls in sequence:
//   SYS_WRITE(1, "Hello from usershell\n", 21);
//   pid = SYS_GETPID();
//   SYS_EXIT(pid);
// The exit-code-as-pid trick lets the kernel's reaper log
// the userland shell's PID via the existing "task <pid>
// exited with code <N>" path — confirms the round-trip
// without needing decimal-to-ASCII conversion in the stub.
//
// Future slices grow this into a real prompt-driven shell
// with TOML reader + ~/.config/duet/shell.toml. For now
// it's enough to demonstrate the spawn pipeline + ring-3
// + multiple syscalls + clean exit.
//
// Spawn happens from main.cpp via core::SpawnElfFile with
// CapSetTrusted() so the SYS_WRITE survives the
// kCapSerialConsole gate.
// clang-format off
constexpr u8 kBinUsershellElfBytes[] = {
    // -- ELF64 header (64 bytes) --
    0x7F, 'E', 'L', 'F',                            // e_ident magic
    0x02,                                           // EI_CLASS = ELFCLASS64
    0x01,                                           // EI_DATA = ELFDATA2LSB
    0x01,                                           // EI_VERSION
    0x00,                                           // EI_OSABI = SYSV
    0x00,                                           // EI_ABIVERSION
    0, 0, 0, 0, 0, 0, 0,                            // padding
    0x02, 0x00,                                     // e_type = ET_EXEC
    0x3E, 0x00,                                     // e_machine = EM_X86_64
    0x01, 0x00, 0x00, 0x00,                         // e_version
    0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, // e_entry = 0x400000
    0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // e_phoff = 64
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // e_shoff = 0
    0x00, 0x00, 0x00, 0x00,                         // e_flags
    0x40, 0x00,                                     // e_ehsize
    0x38, 0x00,                                     // e_phentsize
    0x01, 0x00,                                     // e_phnum = 1
    0x00, 0x00,                                     // e_shentsize
    0x00, 0x00,                                     // e_shnum
    0x00, 0x00,                                     // e_shstrndx

    // -- PT_LOAD program header (56 bytes) --
    0x01, 0x00, 0x00, 0x00,                         // p_type = PT_LOAD
    0x05, 0x00, 0x00, 0x00,                         // p_flags = PF_R | PF_X
    0x78, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // p_offset = 120
    0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, // p_vaddr = 0x400000
    0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, // p_paddr
    0x3D, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // p_filesz = 61
    0x3D, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // p_memsz  = 61
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // p_align  = 1

    // -- Code (40 bytes, file offset 120, va 0x400000) --
    0x48, 0x8D, 0x35, 0x21, 0x00, 0x00, 0x00, // 00: lea rsi, [rip+33] -> msg
    0xBA, 0x15, 0x00, 0x00, 0x00,             // 07: mov edx, 21        (msg len)
    0xBF, 0x01, 0x00, 0x00, 0x00,             // 0C: mov edi, 1         (fd=stdout)
    0xB8, 0x02, 0x00, 0x00, 0x00,             // 11: mov eax, 2         (SYS_WRITE)
    0xCD, 0x80,                               // 16: int 0x80
    0xB8, 0x01, 0x00, 0x00, 0x00,             // 18: mov eax, 1         (SYS_GETPID)
    0xCD, 0x80,                               // 1D: int 0x80           (rax = pid)
    0x89, 0xC7,                               // 1F: mov edi, eax       (status = pid)
    0xB8, 0x00, 0x00, 0x00, 0x00,             // 21: mov eax, 0         (SYS_EXIT)
    0xCD, 0x80,                               // 26: int 0x80

    // -- Message (21 bytes, file offset 160) --
    // "Hello from usershell\n"
    'H', 'e', 'l', 'l', 'o', ' ', 'f', 'r', 'o', 'm', ' ',
    'u', 's', 'e', 'r', 's', 'h', 'e', 'l', 'l', '\n',
};
// clang-format on

// Message-of-the-day shown by the shell on startup. Kept short
// so a 80x40 console has room for the banner + boot log + first
// prompt without scrolling anything important off the top.
constexpr u8 kEtcMotdBytes[] = "------------------------------------------------------------\n"
                               "            DUETOS v0 - WINDOWED DESKTOP SHELL\n"
                               "------------------------------------------------------------\n"
                               " Ctrl+Alt+T   toggle desktop / TTY mode\n"
                               " Ctrl+Alt+F1  shell console     Ctrl+Alt+F2  kernel log\n"
                               " Alt+Tab      cycle window      Alt+F4       close window\n"
                               " Tab          complete          Up/Down      history\n"
                               " help         command list      sysinfo      system status\n"
                               "------------------------------------------------------------\n";

// Default shell profile — auto-sourced by the shell on init.
// Each line dispatches as if typed at the prompt. Lines starting
// with '#' are comments and skipped by the source command.
//
// Under DUETOS_CRTRACE_SURVEY the profile also runs `crtrace show
// 256` so a headless boot dumps the cleanroom-trace ring without
// needing keyboard input. See tools/cleanroom/run-trace-survey.sh.
constexpr u8 kEtcProfileBytes[] = "# DuetOS default profile\n"
                                  "# Runs every time the shell starts.\n"
                                  "set PS1 duetos> \n"
                                  "alias ll ls\n"
                                  "alias l ls\n"
                                  "alias cls clear\n"
#ifdef DUETOS_CRTRACE_SURVEY
                                  "crprobe\n"
                                  "crtrace show 256\n"
#endif
    ;

// Man pages — plain-text per-command help. Each file here lands
// at /etc/man/<name> and is read by the shell's `man` command
// via a straight VfsLookup + cat. Keeping these as real files
// rather than inline strings lets `cat /etc/man/ls` work too,
// and makes the ramfs feel lived-in.
constexpr u8 kManLsBytes[] = "LS [PATH]\n"
                             "  Lists the children of PATH (default /).\n"
                             "  For a file, prints the filename + size.\n"
                             "  /tmp is a writable namespace; other paths are read-only.\n";

constexpr u8 kManCatBytes[] = "CAT PATH\n"
                              "  Prints the contents of PATH.\n"
                              "  Works on ramfs (/etc, /bin) and tmpfs (/tmp).\n";

constexpr u8 kManEchoBytes[] = "ECHO ARG..  [> PATH | >> PATH]\n"
                               "  Prints args separated by single spaces + newline.\n"
                               "  With >, writes to /tmp/<NAME> (replaces).\n"
                               "  With >>, appends. Target must be /tmp.\n";

constexpr u8 kManCpBytes[] = "CP SRC DST\n"
                             "  Copies SRC to DST. DST must be /tmp/<NAME>.\n"
                             "  SRC may be /tmp or any read-only ramfs path.\n";

constexpr u8 kManMvBytes[] = "MV SRC DST\n"
                             "  Renames a /tmp file. Both paths must be /tmp/<NAME>.\n"
                             "  Source is unlinked only after write succeeds.\n";

constexpr u8 kManGrepBytes[] = "GREP PATTERN PATH\n"
                               "  Prints every line of PATH containing PATTERN as a substring.\n"
                               "  Case-sensitive. Empty pattern matches every line.\n";

constexpr u8 kManFindBytes[] = "FIND NAME\n"
                               "  Recursively lists paths whose leaf contains NAME.\n"
                               "  Walks both the static ramfs and the writable tmpfs.\n";

constexpr u8 kManHistoryBytes[] = "HISTORY\n"
                                  "  Prints the last 8 commands (oldest first).\n"
                                  "  !N runs command N, !! repeats the last.\n"
                                  "  Up/Down arrows also cycle history in-place.\n";

constexpr u8 kManAliasBytes[] = "ALIAS NAME CMD   Create or redefine an alias.\n"
                                "ALIAS            List all aliases.\n"
                                "UNALIAS NAME     Remove an alias.\n"
                                "Aliases expand once before dispatch; no recursion.\n";

constexpr u8 kManEnvBytes[] = "SET NAME VALUE   Store an environment variable.\n"
                              "UNSET NAME       Remove a variable.\n"
                              "ENV              List all variables.\n"
                              "Reference a variable in args as $NAME (whole-token only).\n"
                              "Set PS1 to customise the shell prompt.\n";

constexpr u8 kManTimeBytes[] = "TIME CMD..\n"
                               "  Measure wall time of CMD at 10 ms resolution.\n"
                               "  Runs through the full shell pipeline (alias / env /\n"
                               "  redirect all apply).\n";

constexpr u8 kManSourceBytes[] = "SOURCE PATH\n"
                                 "  Runs each line of PATH as a shell command.\n"
                                 "  Blank lines and lines starting with # are skipped.\n"
                                 "  Used to auto-run /etc/profile at boot.\n";

// ------- Trusted tree: / -> {etc/version, bin/hello} -------

constinit RamfsNode k_trusted_etc_version = {
    .name = "version",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = kEtcVersionBytes,
    .file_size = sizeof(kEtcVersionBytes) - 1, // exclude terminating NUL
};

constinit RamfsNode k_trusted_etc_motd = {
    .name = "motd",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = kEtcMotdBytes,
    .file_size = sizeof(kEtcMotdBytes) - 1,
};

constinit RamfsNode k_trusted_etc_profile = {
    .name = "profile",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = kEtcProfileBytes,
    .file_size = sizeof(kEtcProfileBytes) - 1,
};

// /etc/man — one RamfsNode per page. Macro-tight since the
// shape is identical for every entry.
#define MAN_NODE(name_str, bytes_sym)                                                                                  \
    constinit RamfsNode k_man_##bytes_sym = {.name = name_str,                                                         \
                                             .type = RamfsNodeType::kFile,                                             \
                                             .children = nullptr,                                                      \
                                             .file_bytes = bytes_sym,                                                  \
                                             .file_size = sizeof(bytes_sym) - 1}

MAN_NODE("ls", kManLsBytes);
MAN_NODE("cat", kManCatBytes);
MAN_NODE("echo", kManEchoBytes);
MAN_NODE("cp", kManCpBytes);
MAN_NODE("mv", kManMvBytes);
MAN_NODE("grep", kManGrepBytes);
MAN_NODE("find", kManFindBytes);
MAN_NODE("history", kManHistoryBytes);
MAN_NODE("alias", kManAliasBytes);
MAN_NODE("env", kManEnvBytes);
MAN_NODE("time", kManTimeBytes);
MAN_NODE("source", kManSourceBytes);

#undef MAN_NODE

constinit const RamfsNode* const k_trusted_etc_man_children[] = {
    &k_man_kManLsBytes,
    &k_man_kManCatBytes,
    &k_man_kManEchoBytes,
    &k_man_kManCpBytes,
    &k_man_kManMvBytes,
    &k_man_kManGrepBytes,
    &k_man_kManFindBytes,
    &k_man_kManHistoryBytes,
    &k_man_kManAliasBytes,
    &k_man_kManEnvBytes,
    &k_man_kManTimeBytes,
    &k_man_kManSourceBytes,
    nullptr,
};

constinit RamfsNode k_trusted_etc_man_dir = {
    .name = "man",
    .type = RamfsNodeType::kDir,
    .children = k_trusted_etc_man_children,
    .file_bytes = nullptr,
    .file_size = 0,
};

constinit const RamfsNode* const k_trusted_etc_children[] = {
    &k_trusted_etc_version, &k_trusted_etc_motd, &k_trusted_etc_profile, &k_trusted_etc_man_dir, nullptr,
};

constinit RamfsNode k_trusted_etc_dir = {
    .name = "etc",
    .type = RamfsNodeType::kDir,
    .children = k_trusted_etc_children,
    .file_bytes = nullptr,
    .file_size = 0,
};

constinit RamfsNode k_trusted_bin_hello = {
    .name = "hello",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = kBinHelloBytes,
    .file_size = sizeof(kBinHelloBytes) - 1,
};

constinit RamfsNode k_trusted_bin_exit_elf = {
    .name = "exit.elf",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = kBinExitElfBytes,
    .file_size = sizeof(kBinExitElfBytes),
};

// /bin/hello.exe — first PE in the tree. Produced by clang +
// lld-link from userland/apps/hello_pe/hello.c at build time,
// embedded as a byte blob by tools/build/embed-blob.py. The
// kernel PE loader reads these bytes directly; no disk needed.
constinit RamfsNode k_trusted_bin_hello_pe = {
    .name = "hello.exe",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = generated::kBinHelloPeBytes,
    .file_size = generated::kBinHelloPeBytes_len,
};

// /bin/windows-kill.exe — a real Windows executable copied from
// the host as-is. v0 cannot run it (no kernel32, no ntdll).
// Exists so the diagnostic PE path has a real-world image to
// report against — every directory (import, reloc, TLS) is
// non-empty, so every branch of PeReport fires.
constinit RamfsNode k_trusted_bin_winkill = {
    .name = "windows-kill.exe",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = generated::kBinWinKillBytes,
    .file_size = generated::kBinWinKillBytes_len,
};

constinit RamfsNode k_trusted_bin_hello_winapi = {
    .name = "hello_winapi.exe",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = generated::kBinHelloWinapiBytes,
    .file_size = generated::kBinHelloWinapiBytes_len,
};

constinit RamfsNode k_trusted_bin_thread_stress = {
    .name = "thread_stress.exe",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = generated::kBinThreadStressBytes,
    .file_size = generated::kBinThreadStressBytes_len,
};

constinit RamfsNode k_trusted_bin_syscall_stress = {
    .name = "syscall_stress.exe",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = generated::kBinSyscallStressBytes,
    .file_size = generated::kBinSyscallStressBytes_len,
};

// /bin/windowed_hello.exe — first PE that calls
// user32!CreateWindowExA to register a window on the kernel
// compositor. Proves the windowing v0 bridge (SYS_WIN_CREATE /
// SYS_WIN_SHOW / SYS_WIN_MSGBOX, syscalls 58..61) works
// end-to-end from a real PE's Import Directory.
constinit RamfsNode k_trusted_bin_windowed_hello = {
    .name = "windowed_hello.exe",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = generated::kBinWindowedHelloBytes,
    .file_size = generated::kBinWindowedHelloBytes_len,
};

// /bin/customdll_test.exe — DLL-loader end-to-end fixture.
// Imports CustomAdd / CustomMul / CustomVersion from
// customdll.dll (loaded by SpawnPeFile before PeLoad, resolved
// by ResolveImports through the via-DLL path). Exits with
// 0x1234 on success, 0xBAD0 on a call-result mismatch.
constinit RamfsNode k_trusted_bin_customdll_test = {
    .name = "customdll_test.exe",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = generated::kBinCustomDllTestBytes,
    .file_size = generated::kBinCustomDllTestBytes_len,
};

constinit RamfsNode k_trusted_bin_usershell = {
    .name = "usershell.elf",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = kBinUsershellElfBytes,
    .file_size = sizeof(kBinUsershellElfBytes),
};

constinit const RamfsNode* const k_trusted_bin_children[] = {
    &k_trusted_bin_hello,
    &k_trusted_bin_exit_elf,
    &k_trusted_bin_hello_pe,
    &k_trusted_bin_winkill,
    &k_trusted_bin_hello_winapi,
    &k_trusted_bin_thread_stress,
    &k_trusted_bin_syscall_stress,
    &k_trusted_bin_customdll_test,
    &k_trusted_bin_windowed_hello,
    &k_trusted_bin_usershell,
    nullptr,
};

constinit RamfsNode k_trusted_bin_dir = {
    .name = "bin",
    .type = RamfsNodeType::kDir,
    .children = k_trusted_bin_children,
    .file_bytes = nullptr,
    .file_size = 0,
};

// ------- /sys/inspect/<basename> -------
//
// Per-PE summary file populated at boot via PeQuickSummaryTo.
// Each PE we ship in /bin/<basename>.exe gets a paired
// /sys/inspect/<basename>.exe with header counts, image base,
// entry RVA, image size, section count, exports status. 1 KiB
// per file is plenty for the summary (PeQuickSummary's full
// output is ~10 lines).
constexpr u32 kInspectBufferBytes = 1024;
struct InspectSlot
{
    const char* name;
    const u8* file;
    u64 file_len;
    u8 buffer[kInspectBufferBytes];
    u64 cursor;
    RamfsNode node;
};

InspectSlot g_inspect_slots[] = {
    {"hello.exe", generated::kBinHelloPeBytes, generated::kBinHelloPeBytes_len, {}, 0, {}},
    {"hello_winapi.exe", generated::kBinHelloWinapiBytes, generated::kBinHelloWinapiBytes_len, {}, 0, {}},
    {"thread_stress.exe", generated::kBinThreadStressBytes, generated::kBinThreadStressBytes_len, {}, 0, {}},
    {"syscall_stress.exe", generated::kBinSyscallStressBytes, generated::kBinSyscallStressBytes_len, {}, 0, {}},
    {"windowed_hello.exe", generated::kBinWindowedHelloBytes, generated::kBinWindowedHelloBytes_len, {}, 0, {}},
    {"customdll_test.exe", generated::kBinCustomDllTestBytes, generated::kBinCustomDllTestBytes_len, {}, 0, {}},
    {"windows-kill.exe", generated::kBinWinKillBytes, generated::kBinWinKillBytes_len, {}, 0, {}},
};
constexpr u32 kInspectSlotCount = sizeof(g_inspect_slots) / sizeof(g_inspect_slots[0]);

// Children array gets fixed up at init time (constinit on a
// pointer-into-array isn't expressible without designated array
// initialisers). Sized for one slot per PE plus the nullptr
// terminator.
const RamfsNode* g_sys_inspect_children[kInspectSlotCount + 1] = {};

constinit RamfsNode k_sys_inspect_dir = {
    .name = "inspect",
    .type = RamfsNodeType::kDir,
    .children = g_sys_inspect_children,
    .file_bytes = nullptr,
    .file_size = 0,
};

// ------- /sys/syscalls -------
//
// Static text dump of the native syscall name table:
// "<dec_nr>  SYS_FOO\n" lines, ordered as `kSyscallNames[]`
// (i.e. enum order). Snapshotted at boot from `kSyscallNames`,
// then a normal static-bytes ramfs file. 8 KiB caps the dump
// at well above the current ~129-entry table size.
constexpr u32 kSyscallsBufferBytes = 8 * 1024;
u8 g_syscalls_buffer[kSyscallsBufferBytes] = {};
u64 g_syscalls_cursor = 0;

constinit RamfsNode k_sys_syscalls = {
    .name = "syscalls",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = g_syscalls_buffer,
    .file_size = 0,
};

constinit const RamfsNode* const k_sys_children[] = {
    &k_sys_syscalls,
    &k_sys_inspect_dir,
    nullptr,
};

constinit RamfsNode k_sys_dir = {
    .name = "sys",
    .type = RamfsNodeType::kDir,
    .children = k_sys_children,
    .file_bytes = nullptr,
    .file_size = 0,
};

// ------- /proc/cpuhist -------
//
// 60-sample ring of per-tick CPU utilisation derived from
// cumulative `total_ticks` / `idle_ticks` deltas. Each call
// to RamfsCpuhistSnapshot() pushes one sample. With no
// timer-driven sampler wired up yet, the file ships with
// just the boot-time snapshot — header below makes that
// explicit. A future slice can hang RamfsCpuhistSnapshot off
// a 1 Hz timer to fill the ring.
constexpr u32 kCpuhistRingCapacity = 60;
struct CpuhistSample
{
    u64 t_total;     // SchedStats.total_ticks at sample time
    u64 t_idle;      // SchedStats.idle_ticks at sample time
    u8 busy_percent; // (1 - delta_idle/delta_total) * 100, clamped 0..100
};
CpuhistSample g_cpuhist_ring[kCpuhistRingCapacity] = {};
u32 g_cpuhist_count = 0; // saturates at kCpuhistRingCapacity
u32 g_cpuhist_next = 0;  // monotonic; (next % capacity) is write slot

constexpr u32 kCpuhistBufferBytes = 4 * 1024;
u8 g_cpuhist_buffer[kCpuhistBufferBytes] = {};
u64 g_cpuhist_cursor = 0;

constinit RamfsNode k_proc_cpuhist = {
    .name = "cpuhist",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = g_cpuhist_buffer,
    .file_size = 0,
};

// ------- /proc/abi/native + /proc/abi/win32 -------
//
// Two static dumps under /proc/abi:
//   - native: same payload shape as /sys/syscalls (number +
//     name per line), plus a header line. Distinct from
//     /sys/syscalls so consumers that key off path layout
//     (Task Manager → ABI tab) don't have to special-case.
//   - win32: every (DLL, function) the Win32 thunks table
//     knows, formatted as "<dll>!<func>\n". Sourced from
//     Win32ThunksDumpTo so the dump can never drift from the
//     constexpr table.
//
// Both use the same .bss snapshot pattern as boottrace +
// syscalls. Sized to comfortably hold the current tables.
constexpr u32 kAbiNativeBufferBytes = 8 * 1024;
u8 g_abi_native_buffer[kAbiNativeBufferBytes] = {};
u64 g_abi_native_cursor = 0;

constexpr u32 kAbiWin32BufferBytes = 32 * 1024;
u8 g_abi_win32_buffer[kAbiWin32BufferBytes] = {};
u64 g_abi_win32_cursor = 0;

constinit RamfsNode k_proc_abi_native = {
    .name = "native",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = g_abi_native_buffer,
    .file_size = 0,
};

constinit RamfsNode k_proc_abi_win32 = {
    .name = "win32",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = g_abi_win32_buffer,
    .file_size = 0,
};

constinit const RamfsNode* const k_proc_abi_children[] = {
    &k_proc_abi_native,
    &k_proc_abi_win32,
    nullptr,
};

constinit RamfsNode k_proc_abi_dir = {
    .name = "abi",
    .type = RamfsNodeType::kDir,
    .children = k_proc_abi_children,
    .file_bytes = nullptr,
    .file_size = 0,
};

// ------- /proc/boottrace -------
//
// Snapshot of the klog ring at the moment `RamfsBoottraceSnapshot`
// is invoked. Buffer lives in .bss (mutable, zero-initialised).
// `k_proc_boottrace.file_bytes` points at it from boot; the
// `file_size` field starts at 0 and is updated when the snapshot
// runs. After that, /proc/boottrace reads the captured bytes via
// the existing static-file readers — no callback machinery
// needed in the rest of the VFS.
//
// 16 KiB caps the trace at roughly the klog ring's serialised
// size; the snapshot truncates if the ring formats larger than
// that. Plenty for a v0 boot with ~512 ring slots.
constexpr u32 kBoottraceBufferBytes = 16 * 1024;
u8 g_boottrace_buffer[kBoottraceBufferBytes] = {};
u64 g_boottrace_cursor = 0;

constinit RamfsNode k_proc_boottrace = {
    .name = "boottrace",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = g_boottrace_buffer,
    .file_size = 0,
};

constinit const RamfsNode* const k_proc_children[] = {
    &k_proc_boottrace,
    &k_proc_abi_dir,
    &k_proc_cpuhist,
    nullptr,
};

constinit RamfsNode k_proc_dir = {
    .name = "proc",
    .type = RamfsNodeType::kDir,
    .children = k_proc_children,
    .file_bytes = nullptr,
    .file_size = 0,
};

constinit const RamfsNode* const k_trusted_root_children[] = {
    &k_trusted_etc_dir, &k_trusted_bin_dir, &k_proc_dir, &k_sys_dir, nullptr,
};

constinit RamfsNode k_trusted_root = {
    .name = "",
    .type = RamfsNodeType::kDir,
    .children = k_trusted_root_children,
    .file_bytes = nullptr,
    .file_size = 0,
};

// ------- Sandbox tree: / -> welcome.txt -------
//
// Deliberately minimal. A sandboxed process's `/` is THIS node, so
// its entire naming universe consists of "/welcome.txt". Paths
// referring to /etc, /bin, /anything-else will fail at lookup
// because those children do not exist in this root. The sandbox's
// abstraction over "the OS" is exactly what's reachable from here.

constinit RamfsNode k_sandbox_welcome = {
    .name = "welcome.txt",
    .type = RamfsNodeType::kFile,
    .children = nullptr,
    .file_bytes = kWelcomeBytes,
    .file_size = sizeof(kWelcomeBytes) - 1,
};

constinit const RamfsNode* const k_sandbox_root_children[] = {
    &k_sandbox_welcome,
    nullptr,
};

constinit RamfsNode k_sandbox_root = {
    .name = "",
    .type = RamfsNodeType::kDir,
    .children = k_sandbox_root_children,
    .file_bytes = nullptr,
    .file_size = 0,
};

} // namespace

void RamfsInit()
{
    KLOG_TRACE_SCOPE("fs/ramfs", "RamfsInit");
    // Both trees are constinit — nothing to do at runtime. The
    // function exists so (a) the boot sequence has a visible hook
    // for "filesystem is up", and (b) when mutable state lands
    // (inode cache, dentry table), it has a home without requiring
    // callers to change.
    core::Log(core::LogLevel::Info, "fs/ramfs", "ramfs trees seeded");
}

const RamfsNode* RamfsTrustedRoot()
{
    return &k_trusted_root;
}

const RamfsNode* RamfsSandboxRoot()
{
    return &k_sandbox_root;
}

bool RamfsIsDir(const RamfsNode* n)
{
    return n != nullptr && n->type == RamfsNodeType::kDir;
}

const u8* RamfsUsershellElfBytes()
{
    return kBinUsershellElfBytes;
}

u64 RamfsUsershellElfSize()
{
    return sizeof(kBinUsershellElfBytes);
}

namespace
{

// Append a NUL-terminated chunk to the boottrace buffer.
// Truncates at the buffer end — no realloc, no error path.
// Each `chunk` is one of klog's emit fragments (subsystem name,
// separator, message text, newline).
void BoottraceAppend(const char* chunk)
{
    if (chunk == nullptr)
        return;
    while (*chunk != '\0' && g_boottrace_cursor < kBoottraceBufferBytes)
    {
        g_boottrace_buffer[g_boottrace_cursor++] = static_cast<u8>(*chunk++);
    }
}

} // namespace

void RamfsBoottraceSnapshot()
{
    g_boottrace_cursor = 0;
    core::DumpLogRingTo(&BoottraceAppend);
    k_proc_boottrace.file_size = g_boottrace_cursor;
    core::LogWithValue(core::LogLevel::Info, "fs/ramfs", "boottrace snapshot bytes", g_boottrace_cursor);
}

namespace
{

// Append a NUL-terminated C string to the syscalls buffer.
// Truncates at the buffer end without a separate error path —
// the snapshot is best-effort and the buffer is sized well
// above the current table.
void SyscallsAppend(const char* s)
{
    if (s == nullptr)
        return;
    while (*s != '\0' && g_syscalls_cursor < kSyscallsBufferBytes)
    {
        g_syscalls_buffer[g_syscalls_cursor++] = static_cast<u8>(*s++);
    }
}

// Append decimal representation of `v` (no leading zeros).
// Handles 0 as the literal "0". v is u64 so the worst-case is
// 20 characters; we always have enough headroom.
void SyscallsAppendDec(u64 v)
{
    if (v == 0)
    {
        SyscallsAppend("0");
        return;
    }
    char tmp[24] = {};
    u32 i = 0;
    while (v != 0)
    {
        tmp[i++] = static_cast<char>('0' + (v % 10));
        v /= 10;
    }
    // tmp is reversed — emit in correct order.
    while (i > 0)
    {
        --i;
        if (g_syscalls_cursor < kSyscallsBufferBytes)
        {
            g_syscalls_buffer[g_syscalls_cursor++] = static_cast<u8>(tmp[i]);
        }
    }
}

} // namespace

void RamfsSyscallsSnapshot()
{
    g_syscalls_cursor = 0;
    for (u64 i = 0; i < core::kSyscallNamesCount; ++i)
    {
        const auto& e = core::kSyscallNames[i];
        SyscallsAppendDec(e.nr);
        SyscallsAppend("  ");
        SyscallsAppend(e.name);
        SyscallsAppend("\n");
    }
    k_sys_syscalls.file_size = g_syscalls_cursor;
    core::LogWithValue(core::LogLevel::Info, "fs/ramfs", "syscalls snapshot bytes", g_syscalls_cursor);
}

namespace
{

// Generic NUL-terminated append into an arbitrary mutable
// buffer with a separate cursor. Used by both ABI snapshots
// to keep their per-buffer state independent.
void AppendInto(u8* buf, u64& cursor, u64 cap, const char* s)
{
    if (s == nullptr)
        return;
    while (*s != '\0' && cursor < cap)
    {
        buf[cursor++] = static_cast<u8>(*s++);
    }
}

void AppendDecInto(u8* buf, u64& cursor, u64 cap, u64 v)
{
    if (v == 0)
    {
        if (cursor < cap)
            buf[cursor++] = '0';
        return;
    }
    char tmp[24] = {};
    u32 i = 0;
    while (v != 0)
    {
        tmp[i++] = static_cast<char>('0' + (v % 10));
        v /= 10;
    }
    while (i > 0)
    {
        --i;
        if (cursor < cap)
            buf[cursor++] = static_cast<u8>(tmp[i]);
    }
}

void Win32ThunksWriter(const char* chunk)
{
    AppendInto(g_abi_win32_buffer, g_abi_win32_cursor, kAbiWin32BufferBytes, chunk);
}

} // namespace

void RamfsAbiSnapshot()
{
    // Native ABI dump: header + every syscall as
    // "<dec>  SYS_FOO\n". Same shape as /sys/syscalls so a
    // shell consumer can `cat` either path; the header
    // distinguishes the two when stitched into telemetry.
    g_abi_native_cursor = 0;
    AppendInto(g_abi_native_buffer, g_abi_native_cursor, kAbiNativeBufferBytes,
               "# DuetOS native ABI — syscall table\n");
    for (u64 i = 0; i < core::kSyscallNamesCount; ++i)
    {
        const auto& e = core::kSyscallNames[i];
        AppendDecInto(g_abi_native_buffer, g_abi_native_cursor, kAbiNativeBufferBytes, e.nr);
        AppendInto(g_abi_native_buffer, g_abi_native_cursor, kAbiNativeBufferBytes, "  ");
        AppendInto(g_abi_native_buffer, g_abi_native_cursor, kAbiNativeBufferBytes, e.name);
        AppendInto(g_abi_native_buffer, g_abi_native_cursor, kAbiNativeBufferBytes, "\n");
    }
    k_proc_abi_native.file_size = g_abi_native_cursor;

    // Win32 ABI dump: every (DLL, function) the thunks table
    // knows. Win32ThunksDumpTo emits 4 chunks per entry
    // (dll, '!', func, '\n') so the cursor walks lockstep.
    g_abi_win32_cursor = 0;
    AppendInto(g_abi_win32_buffer, g_abi_win32_cursor, kAbiWin32BufferBytes,
               "# DuetOS Win32 ABI — DLL!Function table\n");
    win32::Win32ThunksDumpTo(&Win32ThunksWriter);
    k_proc_abi_win32.file_size = g_abi_win32_cursor;

    core::LogWithValue(core::LogLevel::Info, "fs/ramfs", "abi/native bytes", g_abi_native_cursor);
    core::LogWithValue(core::LogLevel::Info, "fs/ramfs", "abi/win32 bytes", g_abi_win32_cursor);
}

namespace
{
// Per-snapshot scratch — `g_inspect_active` points at the
// InspectSlot whose buffer the writer should append into.
// `PeReportFn` is a free function pointer with no closure, so
// we route through a global. Writes happen in a single thread
// (the boot path) so no locking is needed.
InspectSlot* g_inspect_active = nullptr;

void InspectWriter(const char* chunk)
{
    if (g_inspect_active == nullptr || chunk == nullptr)
        return;
    while (*chunk != '\0' && g_inspect_active->cursor < kInspectBufferBytes)
    {
        g_inspect_active->buffer[g_inspect_active->cursor++] = static_cast<u8>(*chunk++);
    }
}
} // namespace

void RamfsInspectSnapshot()
{
    for (u32 i = 0; i < kInspectSlotCount; ++i)
    {
        InspectSlot& slot = g_inspect_slots[i];
        slot.cursor = 0;
        slot.node.name = slot.name;
        slot.node.type = RamfsNodeType::kFile;
        slot.node.children = nullptr;
        slot.node.file_bytes = slot.buffer;
        g_inspect_active = &slot;
        core::PeQuickSummaryTo(&InspectWriter, slot.file, slot.file_len);
        slot.node.file_size = slot.cursor;
        g_sys_inspect_children[i] = &slot.node;
    }
    g_sys_inspect_children[kInspectSlotCount] = nullptr;
    g_inspect_active = nullptr;
    core::Log(core::LogLevel::Info, "fs/ramfs", "/sys/inspect populated");
}

void RamfsCpuhistSnapshot()
{
    // 1. Push a new sample into the ring. Busy % is computed
    //    relative to the PREVIOUS sample so adjacent calls
    //    measure the gap between them. The first call has no
    //    predecessor so its busy % is 0.
    const auto stats = sched::SchedStatsRead();
    const u32 slot = g_cpuhist_next % kCpuhistRingCapacity;
    u8 busy = 0;
    if (g_cpuhist_count > 0)
    {
        const u32 prev_slot =
            (g_cpuhist_next == 0) ? (kCpuhistRingCapacity - 1) : ((g_cpuhist_next - 1) % kCpuhistRingCapacity);
        const auto& prev = g_cpuhist_ring[prev_slot];
        const u64 d_total = (stats.total_ticks > prev.t_total) ? stats.total_ticks - prev.t_total : 0;
        const u64 d_idle = (stats.idle_ticks > prev.t_idle) ? stats.idle_ticks - prev.t_idle : 0;
        if (d_total > 0)
        {
            const u64 d_busy = (d_total > d_idle) ? d_total - d_idle : 0;
            const u64 percent = (d_busy * 100u) / d_total;
            busy = static_cast<u8>((percent > 100u) ? 100u : percent);
        }
    }
    g_cpuhist_ring[slot] = CpuhistSample{
        .t_total = stats.total_ticks,
        .t_idle = stats.idle_ticks,
        .busy_percent = busy,
    };
    ++g_cpuhist_next;
    if (g_cpuhist_count < kCpuhistRingCapacity)
        ++g_cpuhist_count;

    // 2. Re-render the buffer from the ring, oldest-first.
    g_cpuhist_cursor = 0;
    AppendInto(g_cpuhist_buffer, g_cpuhist_cursor, kCpuhistBufferBytes,
               "# /proc/cpuhist — busy% per snapshot, oldest first.\n");
    AppendInto(g_cpuhist_buffer, g_cpuhist_cursor, kCpuhistBufferBytes,
               "# Sampler is currently driven only by RamfsCpuhistSnapshot()\n");
    AppendInto(g_cpuhist_buffer, g_cpuhist_cursor, kCpuhistBufferBytes,
               "# calls; future slice will hang it off a 1 Hz timer.\n");
    const u32 start = (g_cpuhist_count < kCpuhistRingCapacity) ? 0u : (g_cpuhist_next % kCpuhistRingCapacity);
    for (u32 i = 0; i < g_cpuhist_count; ++i)
    {
        const u32 idx = (start + i) % kCpuhistRingCapacity;
        AppendDecInto(g_cpuhist_buffer, g_cpuhist_cursor, kCpuhistBufferBytes, g_cpuhist_ring[idx].busy_percent);
        AppendInto(g_cpuhist_buffer, g_cpuhist_cursor, kCpuhistBufferBytes, "\n");
    }
    k_proc_cpuhist.file_size = g_cpuhist_cursor;
}

} // namespace duetos::fs
