#!/usr/bin/env bash
#
# Emit a VMware .vmx that boots the DuetOS hybrid ISO with the
# virtual hardware DuetOS actually has drivers for. This encodes
# the config matrix in wiki/tooling/Running-on-VMs.md so the
# non-obvious bits (UEFI + SATA/NVMe-not-PVSCSI + e1000e +
# serial-to-file) are generated, not re-derived per session.
#
# Usage:
#   tools/vm/make-vmware-vmx.sh <duetos.iso> [out.vmx] [vcpus] [ramMB]
# Defaults: out=./duetos.vmx  vcpus=4  ram=2048
#
# UNVERIFIABLE FROM THE DEV CONTAINER: this sandbox has no VMware
# and no nested virt, so this script is text generation only —
# it cannot be boot-tested here. On the first real run, confirm
# from duetos-serial.log via tools/test/boot-log-analyze.sh:
#   - "[hv] hypervisor present vendor=\"VMwareVMware\""
#   - storage came up (drivers/ahci or drivers/nvme online)
#   - "boot : metrics bringup-complete"
# If storage doesn't appear, the .vmx disk controller was
# overridden to LSI/PVSCSI somewhere — DuetOS has no driver for
# those; force SATA or NVMe.

set -euo pipefail

ISO="${1:-}"
OUT="${2:-./duetos.vmx}"
VCPUS="${3:-4}"
RAM="${4:-2048}"

if [ -z "$ISO" ] || [ ! -f "$ISO" ]; then
    echo "usage: $0 <duetos.iso> [out.vmx] [vcpus] [ramMB]" >&2
    exit 2
fi
ISO_ABS="$(cd "$(dirname "$ISO")" && pwd)/$(basename "$ISO")"
SERIAL_LOG="$(cd "$(dirname "$OUT")" 2>/dev/null && pwd || echo .)/duetos-serial.log"

cat > "$OUT" <<EOF
#!/usr/bin/vmware
# Generated by tools/vm/make-vmware-vmx.sh — DuetOS-supported HW only.
.encoding = "UTF-8"
config.version = "8"
virtualHW.version = "19"
displayName = "DuetOS"

# DuetOS is UEFI-first; VMware EFI provides the GOP framebuffer the
# kernel draws on. Do NOT switch to BIOS.
firmware = "efi"

numvcpus = "${VCPUS}"
memsize = "${RAM}"

# Boot medium: the hybrid GRUB ISO on the SATA controller.
sata0.present = "TRUE"
sata0:0.present = "TRUE"
sata0:0.deviceType = "cdrom-image"
sata0:0.fileName = "${ISO_ABS}"
sata0:0.startConnected = "TRUE"

# Scratch disk on SATA (AHCI) — DuetOS drives AHCI + NVMe only;
# the VMware default lsilogic/pvscsi has NO driver. To use NVMe
# instead, swap this block for nvme0.* and a .vmdk.
sata0:1.present = "TRUE"
sata0:1.fileName = "duetos-scratch.vmdk"

# Intel e1000e — DuetOS has the e1000 driver; vmxnet3 has none.
ethernet0.present = "TRUE"
ethernet0.virtualDev = "e1000e"
ethernet0.connectionType = "nat"
ethernet0.addressType = "generated"

# xHCI: DuetOS has an xHCI driver; PS/2 kbd/mouse is also emulated
# so input works regardless.
usb_xhci.present = "TRUE"

# THE diagnostic channel. Every triage rig consumes this file
# (tools/test/boot-log-analyze.sh). Without it you are blind.
serial0.present = "TRUE"
serial0.fileType = "file"
serial0.fileName = "${SERIAL_LOG}"
serial0.startConnected = "TRUE"

# Headless-friendly; flip to "FALSE" for an interactive window.
svga.present = "TRUE"
tools.syncTime = "FALSE"
EOF

echo "wrote $OUT"
echo "  iso        = ${ISO_ABS}"
echo "  vcpus=${VCPUS} ram=${RAM}MB firmware=efi disk=SATA/AHCI nic=e1000e"
echo "  serial log = ${SERIAL_LOG}"
echo
echo "next: create the scratch disk, then boot:"
echo "  vmware-vdiskmanager -c -s 1GB -t 0 duetos-scratch.vmdk   # or via the GUI"
echo "  vmrun start \"$OUT\" nogui   # or open \"$OUT\" in VMware"
echo "then: tools/test/boot-log-analyze.sh \"${SERIAL_LOG}\""
