#!/usr/bin/env bash
# tools/build-hello-pe.sh
#
# Compiles userland/apps/hello_pe/hello.c into a freestanding
# x86_64 Windows PE/COFF executable using host clang +
# lld-link, then embeds the resulting bytes into a C++ header
# via embed_blob.py.
#
# This is the host-side half of the PE subsystem v0 pipeline.
# The kernel PE loader consumes the generated bytes at boot.
#
# Usage:
#     build_hello_pe.sh <repo_root> <out_header>
#
# Arguments are absolute paths. Invoked from CMake via
# add_custom_command — see kernel/CMakeLists.txt.

set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "usage: $0 <repo_root> <out_header>" >&2
    exit 2
fi

REPO_ROOT="$1"
OUT_HEADER="$2"
SRC="${REPO_ROOT}/userland/apps/hello_pe/hello.c"
EMBED="${REPO_ROOT}/tools/embed-blob.py"

WORK_DIR="$(dirname "${OUT_HEADER}")/hello_pe"
mkdir -p "${WORK_DIR}"
OBJ="${WORK_DIR}/hello.obj"
EXE="${WORK_DIR}/hello.exe"

CLANG="${CLANG:-clang}"
LLD_LINK="${LLD_LINK:-lld-link}"

# Freestanding PE: no stdlib, no red zone, no stack canary,
# no unwind tables. -O2 keeps the codegen tight (rip-relative
# addressing for the message). Target MSVC ABI so the produced
# object is a proper PE COFF object that lld-link accepts.
"${CLANG}" \
    --target=x86_64-pc-windows-msvc \
    -c \
    -ffreestanding \
    -nostdlib \
    -fno-stack-protector \
    -fno-builtin \
    -mno-red-zone \
    -fno-asynchronous-unwind-tables \
    -O2 \
    -Wall -Wextra \
    "${SRC}" \
    -o "${OBJ}"

# Link.
#
#   /subsystem:console    — console-subsystem PE (we don't care,
#                           DuetOS ignores Subsystem today, but
#                           we want a real value).
#   /entry:_start         — skip the normal CRT entry; use our
#                           freestanding _start.
#   /nodefaultlib         — no msvcrt, no libcmt, no kernel32.
#   /base:0x400000        — fixed ImageBase; loader v0 does NOT
#                           apply base relocations.
#   /align:4096 /filealign:4096 — page-align sections both in
#                           memory and in the file, so
#                           PointerToRawData == VirtualAddress.
#                           Simplifies the loader: one code
#                           path, no "copy less than a page"
#                           nonsense.
#   /dynamicbase:no       — suppresses the DLL characteristic
#                           that tells loaders to relocate.
#
# The /align warning from lld-link is expected (it's aimed at
# driver authors); we're not using this on Windows, so ignore.
"${LLD_LINK}" \
    /subsystem:console \
    /entry:_start \
    /nodefaultlib \
    /base:0x400000 \
    /align:4096 \
    /filealign:4096 \
    /dynamicbase:no \
    /out:"${EXE}" \
    "${OBJ}" 2>&1 | grep -v "align specified without /driver" || true

if [[ ! -s "${EXE}" ]]; then
    echo "build_hello_pe.sh: lld-link produced no output" >&2
    exit 1
fi

# Emit the generated header the kernel consumes.
python3 "${EMBED}" \
    "${EXE}" \
    "${OUT_HEADER}" \
    kBinHelloPeBytes \
    --namespace "duetos::fs::generated"

echo "build_hello_pe.sh: wrote ${OUT_HEADER} (PE $(stat -c%s "${EXE}") bytes)"
